/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Copyright (c) [2025-2099] Martin (goudingcheng@gmail.com)
 */
package com.github.paohaijiao.mysql;

/**
 * packageName com.github.paohaijiao.mysql
 *
 * @author Martin
 * @version 1.0.0
 * @since 2026/1/31
 */
import com.github.paohaijiao.abs.AbstractTableBuilder;
import com.github.paohaijiao.ddl.index.JQuickIndexDefinition;

public class PostgreSQLTableBuilder extends AbstractTableBuilder {

    @Override
    protected String getCreateTableKeyword() {
        return "CREATE TABLE";
    }

    @Override
    protected String getNotNullKeyword() {
        return "NOT NULL";
    }

    @Override
    protected String getPrimaryKeyKeyword() {
        return "PRIMARY KEY";
    }

    @Override
    protected String getAutoIncrementKeyword() {
        return "GENERATED BY DEFAULT AS IDENTITY";
    }

    @Override
    protected String getDefaultKeyword() {
        return "DEFAULT";
    }

    @Override
    protected String getCommentKeyword() {
        return "--";
    }

    @Override
    protected String getUniqueKeyword() {
        return "UNIQUE";
    }

    @Override
    protected String getIndexKeyword() {
        return "";
    }

    @Override
    protected String getStatementTerminator() {
        return ";";
    }

    @Override
    protected String escapeIdentifier(String identifier) {
        return "\"" + identifier + "\"";
    }

    @Override
    public String buildIndexDefinition(JQuickIndexDefinition index) {
        return "";//todo
    }
}