package com.github.paohaijiao.impl;

/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Copyright (c) [2025-2099] Martin (goudingcheng@gmail.com)
 */

import com.github.paohaijiao.column.JQuickColumnDefinition;
import com.github.paohaijiao.dataType.JQuickDataType;
import com.github.paohaijiao.dataType.JQuickDataTypeConverter;
import com.github.paohaijiao.dataType.impl.JQuickDerbyDataTypeConverter;
import com.github.paohaijiao.dialect.JQuickAbsSQLDialect;
import com.github.paohaijiao.enums.JQuickForeignKeyAction;
import com.github.paohaijiao.extra.JQuickForeignKeyConstraint;
import com.github.paohaijiao.extra.JQuickIndexDefinition;
import com.github.paohaijiao.row.JQuickRow;
import com.github.paohaijiao.table.JQuickTableDefinition;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Apache Derby 方言实现
 * 支持 Derby 数据库的 SQL 语法特性
 *
 * Derby 版本兼容性：
 * - Derby 10.14+
 * - Derby 10.15+
 *
 * 注意：Derby 功能限制：
 * - 不支持 ALTER TABLE DROP COLUMN（10.3+ 支持）
 * - 不支持 TRUNCATE TABLE
 * - 不支持表/列注释
 * - 不支持 SEQUENCE（10.6+ 支持）
 *
 * @author Martin
 * @version 1.0.0
 * @since 2026/4/15
 */
public class JQuickDerbyDialect extends JQuickAbsSQLDialect {

    protected static final String DERBY_QUOTE = "\"";

    private static final String SEQ_SUFFIX = "_SEQ";

    @Override
    protected JQuickDataTypeConverter createDataTypeConvert() {
        return new JQuickDerbyDataTypeConverter();
    }

    @Override
    protected String getQuoteKeyWord() {
        return DERBY_QUOTE;
    }

    @Override
    public String getAutoIncrementKeyword(JQuickTableDefinition tableDefinition) {
        // Derby 使用 GENERATED BY DEFAULT AS IDENTITY
        return "GENERATED BY DEFAULT AS IDENTITY";
    }

    @Override
    protected void appendTableOptions(StringBuilder sql, JQuickTableDefinition table) {
        // Derby 表选项有限
        if (table.getExtensions() != null) {
            // 表空间
            if (table.getExtensions().containsKey("tablespace")) {
                String tablespace = table.getExtensions().get("tablespace").toString();
                sql.append(" IN ").append(quoteIdentifier(table, tablespace));
            }
            // 索引表空间
            if (table.getExtensions().containsKey("indexTablespace")) {
                String indexTablespace = table.getExtensions().get("indexTablespace").toString();
                sql.append(" INDEX IN ").append(quoteIdentifier(table, indexTablespace));
            }
            // 锁定模式
            if (table.getExtensions().containsKey("lockMode")) {
                String lockMode = table.getExtensions().get("lockMode").toString();
                if ("row".equalsIgnoreCase(lockMode)) {
                    sql.append(" LOCKSIZE ROW");
                } else if ("table".equalsIgnoreCase(lockMode)) {
                    sql.append(" LOCKSIZE TABLE");
                }
            }
        }
    }

    @Override
    public String buildCreateTable(JQuickTableDefinition table) {
        StringBuilder sql = new StringBuilder();
        // 临时表
        boolean isTemporary = false;
        if (table.getExtensions() != null && table.getExtensions().containsKey("temporary")) {
            Boolean temporary = (Boolean) table.getExtensions().get("temporary");
            if (temporary != null && temporary) {
                isTemporary = true;
                sql.append("DECLARE GLOBAL TEMPORARY TABLE ");
            } else {
                sql.append("CREATE TABLE ");
            }
        } else {
            sql.append("CREATE TABLE ");
        }
        sql.append(quoteIdentifier(table, table.getTableName())).append(" (\n");
        appendColumnDefinitions(sql, table);
        appendPrimaryKey(sql, table);
        appendUniqueConstraints(sql, table);
        appendForeignKeys(sql, table);
        appendCheckConstraints(sql, table);
        removeTrailingComma(sql);
        sql.append(")");
        appendTableOptions(sql, table);
        // 临时表的额外选项
        if (isTemporary && table.getExtensions() != null) {
            if (table.getExtensions().containsKey("onCommitDeleteRows")) {
                Boolean deleteRows = (Boolean) table.getExtensions().get("onCommitDeleteRows");
                if (deleteRows != null && deleteRows) {
                    sql.append(" ON COMMIT DELETE ROWS");
                } else {
                    sql.append(" ON COMMIT PRESERVE ROWS");
                }
            }
            // 不记录日志
            if (table.getExtensions().containsKey("notLogged")) {
                Boolean notLogged = (Boolean) table.getExtensions().get("notLogged");
                if (notLogged != null && notLogged) {
                    sql.append(" NOT LOGGED");
                }
            }
        }
        // Derby 不支持表注释，添加 SQL 注释作为替代
        if (table.getComment() != null && !table.getComment().isEmpty()) {
            sql.insert(0, "-- " + escapeString(table.getComment()) + "\n");
        }
        return sql.toString();
    }

    /**
     * 追加检查约束
     */
    protected void appendCheckConstraints(StringBuilder sql, JQuickTableDefinition table) {
        if (table.getExtensions() != null && table.getExtensions().containsKey("checkConstraints")) {
            @SuppressWarnings("unchecked")
            List<Map<String, Object>> checks = (List<Map<String, Object>>) table.getExtensions().get("checkConstraints");
            if (checks != null) {
                for (Map<String, Object> check : checks) {
                    String constraintName = (String) check.get("name");
                    String condition = (String) check.get("condition");
                    if (condition != null && !condition.isEmpty()) {
                        sql.append(INDENT);
                        if (constraintName != null && !constraintName.isEmpty()) {
                            sql.append("CONSTRAINT ").append(quoteIdentifier(table, constraintName)).append(" ");
                        }
                        sql.append("CHECK (").append(condition).append(")");
                        sql.append(COMMA).append(NEW_LINE);
                    }
                }
            }
        }
    }

    @Override
    public String buildColumnDefinition(JQuickTableDefinition table, JQuickColumnDefinition column) {
        StringBuilder def = new StringBuilder();
        def.append(quoteIdentifier(table, column.getColumnName())).append(SPACE);
        // 自增列处理
        if (column.isAutoIncrement()) {
            def.append(getDataTypeString(table, column.getDataType()));
            def.append(" ").append(getAutoIncrementKeyword(table));
            // 指定起始值和步长
            if (column.getExtensions() != null) {
                if (column.getExtensions().containsKey("identityStart")) {
                    def.append(" START WITH ").append(column.getExtensions().get("identityStart"));
                }
                if (column.getExtensions().containsKey("identityIncrement")) {
                    def.append(" INCREMENT BY ").append(column.getExtensions().get("identityIncrement"));
                }
            }
        } else {
            def.append(getDataTypeString(table, column.getDataType()));
        }
        appendNullClause(def, column);
        appendDefaultClause(def, column);
        // Derby 不支持列注释，添加 SQL 注释作为替代
        if (column.getComment() != null && !column.getComment().isEmpty()) {
            def.append(" /* ").append(escapeString(column.getComment())).append(" */");
        }
        return def.toString();
    }

    @Override
    protected void appendNullClause(StringBuilder def, JQuickColumnDefinition column) {
        if (!column.isNullable()) {
            def.append(" NOT NULL");
        }
    }

    @Override
    protected void appendDefaultClause(StringBuilder def, JQuickColumnDefinition column) {
        if (column.getDefaultValue() != null && !column.isAutoIncrement()) {
            def.append(" DEFAULT ").append(formatDefaultValue(column.getDefaultValue()));
        }
    }

    @Override
    protected void appendColumnComment(StringBuilder def, JQuickColumnDefinition column) {
        // Derby 不支持列注释，已在 buildColumnDefinition 中处理
    }

    @Override
    protected String getSpecialDefaultKeyword(String value) {
        if (value == null) {
            return null;
        }
        String upperValue = value.toUpperCase();
        if ("CURRENT_TIMESTAMP".equals(upperValue) || "NOW()".equals(upperValue)) {
            return "CURRENT_TIMESTAMP";
        }
        if ("CURRENT_DATE".equals(upperValue)) {
            return "CURRENT_DATE";
        }
        if ("CURRENT_TIME".equals(upperValue)) {
            return "CURRENT_TIME";
        }
        if ("CURRENT_USER".equals(upperValue)) {
            return "CURRENT_USER";
        }
        if ("USER".equals(upperValue)) {
            return "USER";
        }
        return null;
    }

    @Override
    protected String formatBooleanDefault(boolean value) {
        return value ? "TRUE" : "FALSE";
    }

    @Override
    protected String convertForeignKeyAction(JQuickForeignKeyAction action) {
        if (action == null) {
            return "NO ACTION";
        }
        switch (action) {
            case NO_ACTION:
                return "NO ACTION";
            case RESTRICT:
                return "RESTRICT";
            case CASCADE:
                return "CASCADE";
            case SET_NULL:
                return "SET NULL";
            case SET_DEFAULT:
                return "SET DEFAULT";
            default:
                return "NO ACTION";
        }
    }

    @Override
    public String buildModifyColumn(JQuickTableDefinition table, String tableName, JQuickColumnDefinition column) {
        // Derby 10.3+ 支持修改列
        StringBuilder sb = new StringBuilder();
        sb.append("ALTER TABLE ").append(quoteIdentifier(table, tableName));
        sb.append(" ALTER COLUMN ").append(quoteIdentifier(table, column.getColumnName()));
        sb.append(" SET DATA TYPE ").append(getDataTypeString(table, column.getDataType()));
        if (!column.isNullable()) {
            sb.append(" NOT NULL");
        }
        if (column.getDefaultValue() != null && !column.isAutoIncrement()) {
            sb.append(" DEFAULT ").append(formatDefaultValue(column.getDefaultValue()));
        }
        return sb.toString();
    }

    @Override
    public String buildChangeColumn(JQuickTableDefinition table, String tableName, String oldName, JQuickColumnDefinition newColumn) {
        StringBuilder sb = new StringBuilder();
        if (!oldName.equals(newColumn.getColumnName())) {
            // Derby 10.3+ 支持重命名列
            sb.append("ALTER TABLE ").append(quoteIdentifier(table, tableName));
            sb.append(" RENAME COLUMN ").append(quoteIdentifier(table, oldName));
            sb.append(" TO ").append(quoteIdentifier(table, newColumn.getColumnName()));
            sb.append(";\n");
        }
        sb.append("ALTER TABLE ").append(quoteIdentifier(table, tableName));
        sb.append(" ALTER COLUMN ").append(quoteIdentifier(table, newColumn.getColumnName()));
        sb.append(" SET DATA TYPE ").append(getDataTypeString(table, newColumn.getDataType()));
        if (!newColumn.isNullable()) {
            sb.append(" NOT NULL");
        }
        if (newColumn.getDefaultValue() != null && !newColumn.isAutoIncrement()) {
            sb.append(" DEFAULT ").append(formatDefaultValue(newColumn.getDefaultValue()));
        }
        return sb.toString();
    }

    @Override
    public String buildShowCreateTable(JQuickTableDefinition table, String tableName) {
        // Derby 没有 SHOW CREATE TABLE，使用系统表查询
        return "SELECT " +
                "  'CREATE TABLE ' || TABLENAME || ' (...)' " +
                "FROM SYS.SYSTABLES " +
                "WHERE TABLENAME = '" + tableName.toUpperCase() + "'";
    }

    @Override
    public String buildDescribeTable(JQuickTableDefinition table, String tableName) {
        return "SELECT " +
                "  COLUMNNAME, " +
                "  COLUMNDATATYPE, " +
                "  NULLS, " +
                "  COLUMNDEFAULT " +
                "FROM SYS.SYSCOLUMNS " +
                "WHERE REFERENCEID = (SELECT TABLEID FROM SYS.SYSTABLES WHERE TABLENAME = '" + tableName.toUpperCase() + "') " +
                "ORDER BY COLUMNNAME";
    }

    @Override
    public String buildInsert(JQuickTableDefinition table, JQuickRow row) {
        if (row == null || row.isEmpty() || table == null) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        sb.append("INSERT INTO ").append(quoteIdentifier(table, table.getTableName())).append(" (");
        List<String> columns = new ArrayList<>(row.keySet());
        sb.append(columns.stream().map(e -> quoteIdentifier(table, e)).collect(Collectors.joining(", ")));
        sb.append(") VALUES (");
        List<String> values = new ArrayList<>();
        for (String col : columns) {
            values.add(formatValue(row.get(col)));
        }
        sb.append(String.join(", ", values));
        sb.append(")");
        // Derby 使用 IDENTITY_VAL_LOCAL() 获取自增列值
        if (!table.getPrimaryKeys().isEmpty() && hasAutoIncrement(table)) {
            sb.append(";\nSELECT IDENTITY_VAL_LOCAL()");
        }
        return sb.toString();
    }

    @Override
    public String buildUpdate(JQuickTableDefinition table, JQuickRow row, String whereClause) {
        if (row == null || row.isEmpty() || table == null) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        sb.append("UPDATE ").append(quoteIdentifier(table, table.getTableName())).append(" SET ");
        List<String> setClauses = new ArrayList<>();
        for (Map.Entry<String, Object> entry : row.entrySet()) {
            setClauses.add(quoteIdentifier(table, entry.getKey()) + " = " + formatValue(entry.getValue()));
        }
        sb.append(String.join(", ", setClauses));
        if (whereClause != null && !whereClause.trim().isEmpty()) {
            sb.append(" WHERE ").append(whereClause);
        }
        return sb.toString();
    }

    @Override
    public String buildDelete(JQuickTableDefinition table, String whereClause) {
        if (table == null) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        sb.append("DELETE FROM ").append(quoteIdentifier(table, table.getTableName()));
        if (whereClause != null && !whereClause.trim().isEmpty()) {
            sb.append(" WHERE ").append(whereClause);
        }
        return sb.toString();
    }

    @Override
    public String buildSelect(JQuickTableDefinition table, List<String> columns, String whereClause) {
        if (table == null) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        sb.append("SELECT ");
        if (columns == null || columns.isEmpty()) {
            sb.append("*");
        } else {
            sb.append(columns.stream().map(e -> quoteIdentifier(table, e)).collect(Collectors.joining(", ")));
        }
        sb.append(" FROM ").append(quoteIdentifier(table, table.getTableName()));
        if (whereClause != null && !whereClause.trim().isEmpty()) {
            sb.append(" WHERE ").append(whereClause);
        }
        return sb.toString();
    }

    @Override
    public String buildIndex(JQuickTableDefinition table, JQuickIndexDefinition index) {
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE ");
        if (index.isUnique()) {
            sb.append("UNIQUE ");
        }
        sb.append("INDEX ").append(quoteIdentifier(table, index.getIndexName()));
        sb.append(" ON ").append("${tableName}").append(" (");
        sb.append(formatColumnList(table, index.getColumns()));
        sb.append(")");
        return sb.toString();
    }

    /**
     * 检查是否有自增列
     */
    private boolean hasAutoIncrement(JQuickTableDefinition table) {
        return table.getColumns().stream().anyMatch(JQuickColumnDefinition::isAutoIncrement);
    }


    /**
     * 构建创建序列语句
     */
    public String buildCreateSequence(JQuickTableDefinition table, String sequenceName) {
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE SEQUENCE ").append(quoteIdentifier(table, sequenceName));
        Map<String, Object> seqParams = null;
        if (table.getExtensions() != null && table.getExtensions().containsKey("sequenceParams")) {
            @SuppressWarnings("unchecked")
            Map<String, Object> params = (Map<String, Object>) table.getExtensions().get("sequenceParams");
            seqParams = params;
        }
        if (seqParams != null) {
            if (seqParams.containsKey("startWith")) {
                sb.append(" START WITH ").append(seqParams.get("startWith"));
            }
            if (seqParams.containsKey("incrementBy")) {
                sb.append(" INCREMENT BY ").append(seqParams.get("incrementBy"));
            }
            if (seqParams.containsKey("minValue")) {
                sb.append(" MINVALUE ").append(seqParams.get("minValue"));
            }
            if (seqParams.containsKey("maxValue")) {
                sb.append(" MAXVALUE ").append(seqParams.get("maxValue"));
            }
            if (seqParams.containsKey("cache")) {
                sb.append(" CACHE ").append(seqParams.get("cache"));
            }
            if (seqParams.containsKey("cycle")) {
                Boolean cycle = (Boolean) seqParams.get("cycle");
                if (cycle != null && cycle) {
                    sb.append(" CYCLE");
                } else {
                    sb.append(" NO CYCLE");
                }
            }
        }
        return sb.toString();
    }

    /**
     * 构建删除序列语句
     */
    public String buildDropSequence(JQuickTableDefinition table, String sequenceName) {
        return "DROP SEQUENCE " + quoteIdentifier(table, sequenceName) + " RESTRICT";
    }

    /**
     * 构建获取序列下一个值语句
     */
    public String buildGetSequenceNextValue(String sequenceName) {
        return "SELECT NEXT VALUE FOR " + sequenceName + " FROM SYSIBM.SYSDUMMY1";
    }

    /**
     * 构建获取序列当前值语句
     */
    public String buildGetSequenceCurrentValue(String sequenceName) {
        return "SELECT CURRENT VALUE FOR " + sequenceName + " FROM SYSIBM.SYSDUMMY1";
    }


    /**
     * 构建添加列语句
     */
    @Override
    public String buildAddColumn(JQuickTableDefinition table, String tableName, JQuickColumnDefinition column) {
        StringBuilder sb = new StringBuilder();
        sb.append("ALTER TABLE ").append(quoteIdentifier(table, tableName));
        sb.append(" ADD COLUMN ").append(quoteIdentifier(table, column.getColumnName()));
        sb.append(" ").append(getDataTypeString(table, column.getDataType()));
        if (!column.isNullable()) {
            sb.append(" NOT NULL");
        }
        if (column.getDefaultValue() != null && !column.isAutoIncrement()) {
            sb.append(" DEFAULT ").append(formatDefaultValue(column.getDefaultValue()));
        }

        return sb.toString();
    }

    /**
     * 构建删除列语句（Derby 10.3+ 支持）
     */
    @Override
    public String buildDropColumn(JQuickTableDefinition table, String tableName, String columnName) {
        return "ALTER TABLE " + quoteIdentifier(table, tableName) + " DROP COLUMN " + quoteIdentifier(table, columnName) + " RESTRICT";
    }

    /**
     * 构建重命名列语句（Derby 10.3+ 支持）
     */
    public String buildRenameColumn(JQuickTableDefinition table, String tableName, String oldName, String newName) {
        return "ALTER TABLE " + quoteIdentifier(table, tableName) + " RENAME COLUMN " + quoteIdentifier(table, oldName) + " TO " + quoteIdentifier(table, newName);
    }

    /**
     * 构建设置 NOT NULL 语句
     */
    public String buildSetNotNull(JQuickTableDefinition table, String tableName, String columnName) {
        return "ALTER TABLE " + quoteIdentifier(table, tableName) + " ALTER COLUMN " + quoteIdentifier(table, columnName) + " NOT NULL";
    }

    /**
     * 构建删除 NOT NULL 语句
     */
    public String buildDropNotNull(JQuickTableDefinition table, String tableName, String columnName) {
        return "ALTER TABLE " + quoteIdentifier(table, tableName) + " ALTER COLUMN " + quoteIdentifier(table, columnName) + " NULL";
    }

    /**
     * 构建设置默认值语句
     */
    public String buildSetDefaultValue(JQuickTableDefinition table, String tableName, String columnName, Object defaultValue) {
        return "ALTER TABLE " + quoteIdentifier(table, tableName) + " ALTER COLUMN " + quoteIdentifier(table, columnName) + " SET DEFAULT " + formatDefaultValue(defaultValue);
    }

    /**
     * 构建删除默认值语句
     */
    public String buildDropDefaultValue(JQuickTableDefinition table, String tableName, String columnName) {
        return "ALTER TABLE " + quoteIdentifier(table, tableName) + " ALTER COLUMN " + quoteIdentifier(table, columnName) + " DROP DEFAULT";
    }
    /**
     * 构建删除表语句
     */
    @Override
    public String buildDropTable(JQuickTableDefinition table, String tableName, boolean ifExists) {
        StringBuilder sb = new StringBuilder();
        if (ifExists) {
            // Derby 没有 IF EXISTS，需要先检查
            sb.append("BEGIN\n");
            sb.append("  IF (SELECT COUNT(*) FROM SYS.SYSTABLES WHERE TABLENAME = '")
                    .append(tableName.toUpperCase()).append("') > 0 THEN\n");
            sb.append("    DROP TABLE ").append(quoteIdentifier(table, tableName)).append(";\n");
            sb.append("  END IF\n");
            sb.append("END");
        } else {
            sb.append("DROP TABLE ").append(quoteIdentifier(table, tableName));
        }
        return sb.toString();
    }

    /**
     * 构建清空表语句（Derby 不支持 TRUNCATE，使用 DELETE）
     */
    @Override
    public String buildTruncateTable(JQuickTableDefinition table, String tableName) {
        return "DELETE FROM " + quoteIdentifier(table, tableName);
    }

    /**
     * 构建重命名表语句
     */
    @Override
    public String buildRenameTable(JQuickTableDefinition table, String oldName, String newName) {
        return "RENAME TABLE " + quoteIdentifier(table, oldName) +
                " TO " + quoteIdentifier(table, newName);
    }

    /**
     * 构建添加主键语句
     */
    public String buildAddPrimaryKey(JQuickTableDefinition table, String tableName, String constraintName, List<String> columns) {
        StringBuilder sb = new StringBuilder("ALTER TABLE ");
        sb.append(quoteIdentifier(table, tableName));
        sb.append(" ADD CONSTRAINT ");
        if (constraintName != null && !constraintName.isEmpty()) {
            sb.append(quoteIdentifier(table, constraintName)).append(" ");
        }
        sb.append("PRIMARY KEY (").append(formatColumnList(table, columns)).append(")");
        return sb.toString();
    }

    /**
     * 构建添加唯一约束语句
     */
    public String buildAddUniqueConstraint(JQuickTableDefinition table, String tableName, String constraintName, List<String> columns) {
        StringBuilder sb = new StringBuilder("ALTER TABLE ");
        sb.append(quoteIdentifier(table, tableName));
        sb.append(" ADD CONSTRAINT ");
        if (constraintName != null && !constraintName.isEmpty()) {
            sb.append(quoteIdentifier(table, constraintName)).append(" ");
        }
        sb.append("UNIQUE (").append(formatColumnList(table, columns)).append(")");
        return sb.toString();
    }

    /**
     * 构建添加外键语句
     */
    public String buildAddForeignKey(JQuickTableDefinition table, String tableName, JQuickForeignKeyConstraint fk) {
        StringBuilder sb = new StringBuilder("ALTER TABLE ");
        sb.append(quoteIdentifier(table, tableName));
        sb.append(" ADD CONSTRAINT ");
        if (fk.getConstraintName() != null && !fk.getConstraintName().isEmpty()) {
            sb.append(quoteIdentifier(table, fk.getConstraintName())).append(" ");
        }
        sb.append("FOREIGN KEY (").append(formatColumnList(table, fk.getColumns()));
        sb.append(") REFERENCES ").append(quoteIdentifier(table, fk.getReferencedTable()));
        sb.append(" (").append(formatColumnList(table, fk.getReferencedColumns())).append(")");
        if (fk.getOnDelete() != null) {
            sb.append(" ON DELETE ").append(convertForeignKeyAction(fk.getOnDelete()));
        }
        if (fk.getOnUpdate() != null) {
            sb.append(" ON UPDATE ").append(convertForeignKeyAction(fk.getOnUpdate()));
        }
        return sb.toString();
    }

    /**
     * 构建删除约束语句
     */
    public String buildDropConstraint(JQuickTableDefinition table, String tableName, String constraintName) {
        return "ALTER TABLE " + quoteIdentifier(table, tableName) +
                " DROP CONSTRAINT " + quoteIdentifier(table, constraintName);
    }


    /**
     * 构建分页查询语句（使用 ROW_NUMBER）
     */
    public String buildPaginationQuery(JQuickTableDefinition table, List<String> columns, String whereClause, String orderBy, int offset, int limit) {
        StringBuilder sql = new StringBuilder();
        sql.append("SELECT * FROM (\n");
        sql.append("  SELECT ROW_NUMBER() OVER (").append(orderBy != null ? "ORDER BY " + orderBy : "").append(") AS row_num,\n");
        sql.append("    ").append(columns != null && !columns.isEmpty() ?
                columns.stream().map(c -> quoteIdentifier(table, c)).collect(Collectors.joining(", ")) : "*");
        sql.append("\n  FROM ").append(quoteIdentifier(table, table.getTableName()));
        if (whereClause != null && !whereClause.isEmpty()) {
            sql.append("\n  WHERE ").append(whereClause);
        }
        sql.append("\n) AS t\n");
        sql.append("WHERE row_num > ").append(offset);
        if (limit > 0) {
            sql.append(" AND row_num <= ").append(offset + limit);
        }
        return sql.toString();
    }

    /**
     * 构建 FETCH FIRST 查询语句
     */
    public String buildFetchFirstQuery(JQuickTableDefinition table, List<String> columns, String whereClause, String orderBy, int limit) {
        StringBuilder sql = new StringBuilder();
        sql.append(buildSelect(table, columns, whereClause));
        if (orderBy != null && !orderBy.isEmpty()) {
            sql.append(" ORDER BY ").append(orderBy);
        }
        sql.append(" FETCH FIRST ").append(limit).append(" ROWS ONLY");
        return sql.toString();
    }

    /**
     * 构建更新统计信息语句
     */
    public String buildUpdateStatistics(JQuickTableDefinition table, String tableName) {
        return "CALL SYSCS_UTIL.SYSCS_UPDATE_STATISTICS('APP', '" + tableName.toUpperCase() + "', NULL)";
    }

    /**
     * 构建压缩表语句
     */
    public String buildCompressTable(JQuickTableDefinition table, String tableName) {
        return "CALL SYSCS_UTIL.SYSCS_COMPRESS_TABLE('APP', '" + tableName.toUpperCase() + "', 1)";
    }

    /**
     * 构建冻结表语句
     */
    public String buildFreezeTable(JQuickTableDefinition table, String tableName) {
        return "CALL SYSCS_UTIL.SYSCS_FREEZE_TABLE('APP', '" + tableName.toUpperCase() + "')";
    }

    /**
     * 构建解冻表语句
     */
    public String buildUnfreezeTable(JQuickTableDefinition table, String tableName) {
        return "CALL SYSCS_UTIL.SYSCS_UNFREEZE_TABLE('APP', '" + tableName.toUpperCase() + "')";
    }


    /**
     * 构建查询当前数据库语句
     */
    public String buildCurrentDatabase() {
        return "SELECT CURRENT SCHEMA FROM SYSIBM.SYSDUMMY1";
    }

    /**
     * 构建查询当前用户语句
     */
    public String buildCurrentUser() {
        return "SELECT CURRENT_USER FROM SYSIBM.SYSDUMMY1";
    }

    /**
     * 构建查询所有表语句
     */
    public String buildShowTables() {
        return "SELECT TABLENAME FROM SYS.SYSTABLES WHERE TABLETYPE = 'T'";
    }

    /**
     * 构建查询版本语句
     */
    public String buildVersion() {
        return "SELECT GETDATABASE() FROM SYSIBM.SYSDUMMY1";
    }

    /**
     * 构建检查数据库语句
     */
    public String buildCheckDatabase() {
        return "CALL SYSCS_UTIL.SYSCS_CHECK_TABLE('APP', 'SYS.SYSTABLES')";
    }

    /**
     * 构建备份数据库语句
     */
    public String buildBackupDatabase(String backupDir) {
        return "CALL SYSCS_UTIL.SYSCS_BACKUP_DATABASE('" + backupDir + "')";
    }

    /**
     * 构建导出表语句
     */
    public String buildExportTable(String tableName, String fileName) {
        return "CALL SYSCS_UTIL.SYSCS_EXPORT_TABLE('APP', '" + tableName + "', '" + fileName + "', null, null, null)";
    }

    /**
     * 构建导入表语句
     */
    public String buildImportTable(String tableName, String fileName) {
        return "CALL SYSCS_UTIL.SYSCS_IMPORT_TABLE('APP', '" + tableName + "', '" + fileName + "', null, null, null, 0)";
    }
    /**
     * 构建设置隔离级别语句
     */
    public String buildSetIsolationLevel(String level) {
        return "SET ISOLATION " + level;
    }

    /**
     * 构建显示锁信息语句
     */
    public String buildShowLocks() {
        return "SELECT * FROM SYS.SYSLOCKS";
    }
}
