package com.github.paohaijiao.impl;
/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Copyright (c) [2025-2099] Martin (goudingcheng@gmail.com)
 */

import com.github.paohaijiao.column.JQuickColumnDefinition;
import com.github.paohaijiao.connector.JQuickDataSourceConnector;
import com.github.paohaijiao.dataType.JQuickDataType;
import com.github.paohaijiao.dataType.JQuickDataTypeConverter;
import com.github.paohaijiao.dataType.enums.JQuickDataTypeFamily;
import com.github.paohaijiao.dataType.impl.JQuickOceanBaseDataTypeConverter;
import com.github.paohaijiao.dialect.JQuickAbsSQLDialect;
import com.github.paohaijiao.enums.JQuickForeignKeyAction;
import com.github.paohaijiao.extra.JQuickForeignKeyConstraint;
import com.github.paohaijiao.extra.JQuickIndexDefinition;
import com.github.paohaijiao.extra.JQuickPrimaryKeyConstraint;
import com.github.paohaijiao.extra.JQuickUniqueConstraint;
import com.github.paohaijiao.row.JQuickRow;
import com.github.paohaijiao.table.JQuickTableDefinition;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * OceanBase 方言实现
 * 支持 OceanBase 数据库的 MySQL 和 Oracle 两种兼容模式
 * <p>
 * OceanBase 版本兼容性：
 * - OceanBase 3.x
 * - OceanBase 4.x
 * <p>
 * 主要特性：
 * - 支持 MySQL 和 Oracle 两种兼容模式
 * - 分布式架构，支持多租户
 * - 支持全局索引和局部索引
 * - 支持表分组（Table Group）
 * - 支持数据压缩
 * - 支持副本策略
 *
 * @author Martin
 * @version 1.0.0
 * @since 2026/4/15
 */
public class JQuickOceanBaseDialect extends JQuickAbsSQLDialect {

    // 兼容模式
    public static final String MODE_MYSQL = "MYSQL";
    public static final String MODE_ORACLE = "ORACLE";
    protected static final String OB_QUOTE = "`";
    private final String mode;

    /**
     * 默认使用 MySQL 模式
     */
    public JQuickOceanBaseDialect() {
        this(MODE_MYSQL);
    }

    /**
     * 指定模式创建方言
     *
     * @param mode MODE_MYSQL 或 MODE_ORACLE
     */
    public JQuickOceanBaseDialect(String mode) {
        this.mode = mode == null ? MODE_MYSQL : mode.toUpperCase();
    }

    public String getMode() {
        return mode;
    }

    @Override
    protected JQuickDataTypeConverter createDataTypeConvert() {
        return new JQuickOceanBaseDataTypeConverter(mode);
    }

    @Override
    protected String getQuoteKeyWord() {
        return OB_QUOTE;
    }

    @Override
    public String getAutoIncrementKeyword(JQuickTableDefinition tableDefinition) {
        if (MODE_ORACLE.equals(mode)) {
            return "GENERATED BY DEFAULT AS IDENTITY";
        }
        return "AUTO_INCREMENT";
    }

    @Override
    protected void appendTableOptions(StringBuilder sql, JQuickTableDefinition table) {
        if (table.getExtensions() == null) {
            return;
        }

        if (MODE_ORACLE.equals(mode)) {
            appendOracleTableOptions(sql, table);
        } else {
            appendMySQLTableOptions(sql, table);
        }
    }

    @Override
    public String getDriverClass(JQuickDataSourceConnector connector) {
        if (connector != null && connector.getDriverClass() != null && !connector.getDriverClass().trim().isEmpty()) {
            return connector.getDriverClass();
        }
        String mode = connector.getByKeyStr("mode");
        boolean isOracleMode = "oracle".equalsIgnoreCase(mode);
        if (isOracleMode) {
            return "com.oceanbase.jdbc.Driver";
        } else {
            return "com.oceanbase.jdbc.Driver";
        }
    }

    @Override
    public String getUrl(JQuickDataSourceConnector connector) {
        if (connector == null) {
            throw new IllegalArgumentException("Connector cannot be null");
        }
        if (connector.getUrl() != null && !connector.getUrl().trim().isEmpty()) {
            return connector.getUrl();
        }
        String host = connector.getHost();
        String port = connector.getPort();
        String database = connector.getSchema();      // 数据库名（MySQL模式）/ Schema名（Oracle模式）
        String username = connector.getUsername();
        String password = connector.getPassword();
        if (host == null || host.trim().isEmpty()) {
            throw new IllegalStateException("Host is required for OceanBase connection");
        }
        String mode = connector.getByKeyStr("mode");   // mysql 或 oracle
        boolean isOracleMode = "oracle".equalsIgnoreCase(mode);
        String effectivePort;
        if (port != null && !port.trim().isEmpty()) {
            effectivePort = port;
        } else if (isOracleMode) {
            effectivePort = "1521";
        } else {
            effectivePort = "2881";
        }
        StringBuilder url = new StringBuilder();
        if (isOracleMode) {
            url.append("jdbc:oceanbase:oracle://").append(host).append(":").append(effectivePort);
        } else {
            url.append("jdbc:oceanbase://").append(host).append(":").append(effectivePort);
        }
        if (database != null && !database.trim().isEmpty()) {
            url.append("/").append(database);
        } else {
            url.append("/");
        }
        boolean hasParams = false;
        if (username != null && !username.trim().isEmpty()) {
            url.append("?user=").append(username);
            hasParams = true;
        }

        if (password != null && !password.trim().isEmpty()) {
            url.append(hasParams ? "&" : "?").append("password=").append(password);
            hasParams = true;
        }
        if (hasParams) {
            url.append("&useUnicode=true");
            url.append("&characterEncoding=UTF-8");
        } else {
            url.append("?useUnicode=true");
            url.append("&characterEncoding=UTF-8");
        }
        String useOldAlias = connector.getByKeyStr("useOldAliasMetadataBehavior");
        if (useOldAlias != null && !useOldAlias.isEmpty()) {
            url.append("&useOldAliasMetadataBehavior=").append(useOldAlias);
        } else {
            url.append("&useOldAliasMetadataBehavior=true");
        }
        return url.toString();
    }

    /**
     * MySQL 模式表选项
     */
    private void appendMySQLTableOptions(StringBuilder sql, JQuickTableDefinition table) {
        Map<String, Object> ext = table.getExtensions();

        // 表分组（OceanBase 特有）
        if (ext.containsKey("tableGroup")) {
            String tableGroup = ext.get("tableGroup").toString();
            sql.append(" TABLEGROUP = ").append(quoteIdentifier(table, tableGroup));
        }

        // 数据压缩
        if (ext.containsKey("compress")) {
            String compress = ext.get("compress").toString();
            sql.append(" COMPRESS = '").append(compress).append("'");
        }

        // 副本数
        if (ext.containsKey("replicaNum")) {
            Integer replicaNum = (Integer) ext.get("replicaNum");
            sql.append(" REPLICA_NUM = ").append(replicaNum);
        }

        // 主区域
        if (ext.containsKey("primaryZone")) {
            String primaryZone = ext.get("primaryZone").toString();
            sql.append(" PRIMARY_ZONE = '").append(primaryZone).append("'");
        }

        // 位置标签
        if (ext.containsKey("locality")) {
            String locality = ext.get("locality").toString();
            sql.append(" LOCALITY = '").append(locality).append("'");
        }

        // 行格式
        if (ext.containsKey("rowFormat")) {
            String rowFormat = ext.get("rowFormat").toString();
            sql.append(" ROW_FORMAT = ").append(rowFormat);
        }

        // 块大小
        if (ext.containsKey("blockSize")) {
            Integer blockSize = (Integer) ext.get("blockSize");
            sql.append(" BLOCK_SIZE = ").append(blockSize);
        }
    }

    /**
     * Oracle 模式表选项
     */
    private void appendOracleTableOptions(StringBuilder sql, JQuickTableDefinition table) {
        Map<String, Object> ext = table.getExtensions();

        // 表空间
        if (ext.containsKey("tablespace")) {
            String tablespace = ext.get("tablespace").toString();
            sql.append(" TABLESPACE ").append(quoteIdentifier(table, tablespace));
        }

        // 存储参数
        if (ext.containsKey("storage")) {
            @SuppressWarnings("unchecked")
            Map<String, Object> storage = (Map<String, Object>) ext.get("storage");
            if (storage != null && !storage.isEmpty()) {
                sql.append(" STORAGE (");
                boolean first = true;
                for (Map.Entry<String, Object> entry : storage.entrySet()) {
                    if (!first) sql.append(", ");
                    sql.append(entry.getKey()).append(" ").append(entry.getValue());
                    first = false;
                }
                sql.append(")");
            }
        }

        // 压缩
        if (ext.containsKey("compress")) {
            String compress = ext.get("compress").toString();
            sql.append(" COMPRESS ").append(compress);
        }

        // 日志选项
        if (ext.containsKey("logging")) {
            Boolean logging = (Boolean) ext.get("logging");
            if (logging != null) {
                sql.append(logging ? " LOGGING" : " NOLOGGING");
            }
        }

        // 缓存选项
        if (ext.containsKey("cache")) {
            Boolean cache = (Boolean) ext.get("cache");
            if (cache != null && cache) {
                sql.append(" CACHE");
            } else {
                sql.append(" NOCACHE");
            }
        }
    }

    @Override
    public String buildCreateTable(JQuickTableDefinition table) {
        if (MODE_ORACLE.equals(mode)) {
            return buildOracleCreateTable(table);
        }
        return buildMySQLCreateTable(table);
    }

    /**
     * MySQL 模式建表语句
     */
    private String buildMySQLCreateTable(JQuickTableDefinition table) {
        StringBuilder sql = new StringBuilder();

        // 临时表
        if (isTemporary(table)) {
            sql.append("CREATE TEMPORARY TABLE ");
        } else {
            sql.append("CREATE TABLE ");
        }

        // IF NOT EXISTS
        if (ifNotExists(table)) {
            sql.append("IF NOT EXISTS ");
        }

        sql.append(quoteIdentifier(table, table.getTableName()));
        sql.append(" (\n");
        // 列定义
        appendMySQLColumnDefinitions(sql, table);
        // 约束定义
        appendConstraints(sql, table);
        sql.append(")");
        // 表选项
        appendTableOptions(sql, table);

        // 表注释
        if (table.getComment() != null && !table.getComment().isEmpty()) {
            sql.append(" COMMENT = '").append(escapeString(table.getComment())).append("'");
        }

        // 分区
        appendPartition(sql, table);

        return sql.toString();
    }

    /**
     * Oracle 模式建表语句
     */
    private String buildOracleCreateTable(JQuickTableDefinition table) {
        StringBuilder sql = new StringBuilder();

        // 临时表
        if (isTemporary(table)) {
            sql.append("CREATE GLOBAL TEMPORARY TABLE ");
        } else {
            sql.append("CREATE TABLE ");
        }

        sql.append(quoteIdentifier(table, table.getTableName()));
        sql.append(" (\n");
        // 列定义
        appendOracleColumnDefinitions(sql, table);

        // 约束定义
        appendConstraints(sql, table);

        sql.append(")");
        // 表选项
        appendTableOptions(sql, table);

        // 临时表选项
        if (isTemporary(table) && table.getExtensions() != null) {
            if (table.getExtensions().containsKey("onCommitPreserveRows")) {
                Boolean preserve = (Boolean) table.getExtensions().get("onCommitPreserveRows");
                if (preserve != null && preserve) {
                    sql.append(" ON COMMIT PRESERVE ROWS");
                } else {
                    sql.append(" ON COMMIT DELETE ROWS");
                }
            }
        }

        // 表注释
        String tableComment = buildOracleTableComment(table);
        if (tableComment != null && !tableComment.isEmpty()) {
            sql.append(";\n").append(tableComment);
        }

        return sql.toString();
    }

    /**
     * MySQL 模式列定义
     */
    private void appendMySQLColumnDefinitions(StringBuilder sql, JQuickTableDefinition table) {
        List<JQuickColumnDefinition> columns = table.getColumns();
        for (int i = 0; i < columns.size(); i++) {
            JQuickColumnDefinition column = columns.get(i);
            sql.append(INDENT).append(quoteIdentifier(table, column.getColumnName()))
                    .append(" ").append(getDataTypeString(table, column.getDataType()));

            // NOT NULL
            if (!column.isNullable()) {
                sql.append(" NOT NULL");
            }

            // NULL
            if (column.isNullable() && column.getDefaultValue() == null) {
                sql.append(" NULL");
            }

            // 自增
            if (column.isAutoIncrement()) {
                sql.append(" AUTO_INCREMENT");
            }

            // 默认值
            if (column.getDefaultValue() != null && !column.isAutoIncrement()) {
                sql.append(" DEFAULT ").append(formatDefaultValue(column.getDefaultValue()));
            }

            // 列注释
            if (column.getComment() != null && !column.getComment().isEmpty()) {
                sql.append(" COMMENT '").append(escapeString(column.getComment())).append("'");
            }

            if (i < columns.size() - 1) {
                sql.append(",");
            }
            sql.append(NEW_LINE);
        }
    }

    /**
     * Oracle 模式列定义
     */
    private void appendOracleColumnDefinitions(StringBuilder sql, JQuickTableDefinition table) {
        List<JQuickColumnDefinition> columns = table.getColumns();
        for (int i = 0; i < columns.size(); i++) {
            JQuickColumnDefinition column = columns.get(i);
            sql.append(INDENT).append(quoteIdentifier(table, column.getColumnName()))
                    .append(" ").append(getDataTypeString(table, column.getDataType()));

            // NOT NULL
            if (!column.isNullable()) {
                sql.append(" NOT NULL");
            }

            // 自增
            if (column.isAutoIncrement()) {
                sql.append(" ").append(getAutoIncrementKeyword(table));
            }

            // 默认值
            if (column.getDefaultValue() != null && !column.isAutoIncrement()) {
                sql.append(" DEFAULT ").append(formatDefaultValue(column.getDefaultValue()));
            }

            if (i < columns.size() - 1) {
                sql.append(",");
            }
            sql.append(NEW_LINE);
        }
    }

    /**
     * 追加约束定义
     */
    private void appendConstraints(StringBuilder sql, JQuickTableDefinition table) {
        boolean hasColumns = !table.getColumns().isEmpty();

        // 主键
        if (!table.getPrimaryKeys().isEmpty()) {
            if (hasColumns) {
                sql.append(COMMA).append(NEW_LINE);
            }
            sql.append(INDENT).append(buildPrimaryKey(table, table.getPrimaryKeys().get(0)));
        }

        // 唯一约束
        for (JQuickUniqueConstraint uc : table.getUniqueConstraints()) {
            sql.append(COMMA).append(NEW_LINE);
            sql.append(INDENT).append(buildUniqueConstraint(table, uc));
        }

        // 外键
        for (JQuickForeignKeyConstraint fk : table.getForeignKeys()) {
            sql.append(COMMA).append(NEW_LINE);
            sql.append(INDENT).append(buildForeignKey(table, fk));
        }
    }

    /**
     * 追加分区
     */
    private void appendPartition(StringBuilder sql, JQuickTableDefinition table) {
        if (table.getExtensions() == null) {
            return;
        }

        Map<String, Object> ext = table.getExtensions();

        // 范围分区
        if (ext.containsKey("rangePartition")) {
            @SuppressWarnings("unchecked")
            Map<String, Object> partition = (Map<String, Object>) ext.get("rangePartition");
            sql.append("\nPARTITION BY RANGE (").append(partition.get("column")).append(") (");

            @SuppressWarnings("unchecked")
            List<Map<String, String>> partitions = (List<Map<String, String>>) partition.get("partitions");
            if (partitions != null) {
                for (int i = 0; i < partitions.size(); i++) {
                    Map<String, String> p = partitions.get(i);
                    sql.append("\n  PARTITION ").append(p.get("name"))
                            .append(" VALUES LESS THAN (").append(p.get("value")).append(")");
                    if (i < partitions.size() - 1) {
                        sql.append(",");
                    }
                }
            }
            sql.append("\n)");
        }

        // 哈希分区
        if (ext.containsKey("hashPartition")) {
            @SuppressWarnings("unchecked")
            Map<String, Object> partition = (Map<String, Object>) ext.get("hashPartition");
            sql.append("\nPARTITION BY HASH (").append(partition.get("column")).append(")")
                    .append("\nPARTITIONS ").append(partition.get("partitions"));
        }

        // 列表分区
        if (ext.containsKey("listPartition")) {
            @SuppressWarnings("unchecked")
            Map<String, Object> partition = (Map<String, Object>) ext.get("listPartition");
            sql.append("\nPARTITION BY LIST (").append(partition.get("column")).append(") (");

            @SuppressWarnings("unchecked")
            List<Map<String, Object>> partitions = (List<Map<String, Object>>) partition.get("partitions");
            if (partitions != null) {
                for (int i = 0; i < partitions.size(); i++) {
                    Map<String, Object> p = partitions.get(i);
                    sql.append("\n  PARTITION ").append(p.get("name"))
                            .append(" VALUES IN (");
                    @SuppressWarnings("unchecked")
                    List<String> values = (List<String>) p.get("values");
                    sql.append(values.stream().map(v -> "'" + v + "'").collect(Collectors.joining(", ")));
                    sql.append(")");
                    if (i < partitions.size() - 1) {
                        sql.append(",");
                    }
                }
            }
            sql.append("\n)");
        }
    }

    @Override
    public String buildColumnDefinition(JQuickTableDefinition table, JQuickColumnDefinition column) {
        StringBuilder def = new StringBuilder();
        def.append(quoteIdentifier(table, column.getColumnName())).append(SPACE);
        def.append(getDataTypeString(table, column.getDataType()));

        if (!column.isNullable()) {
            def.append(" NOT NULL");
        }

        if (column.getDefaultValue() != null && !column.isAutoIncrement()) {
            def.append(" DEFAULT ").append(formatDefaultValue(column.getDefaultValue()));
        }

        return def.toString();
    }

    @Override
    public String buildPrimaryKey(JQuickTableDefinition table, JQuickPrimaryKeyConstraint pk) {
        StringBuilder sb = new StringBuilder();
        if (pk.getConstraintName() != null && !pk.getConstraintName().isEmpty()) {
            sb.append("CONSTRAINT ").append(quoteIdentifier(table, pk.getConstraintName())).append(SPACE);
        }
        sb.append("PRIMARY KEY (");
        sb.append(formatColumnList(table, pk.getColumns()));
        sb.append(")");
        // 全局索引（OceanBase MySQL 模式特有）
        if (MODE_MYSQL.equals(mode) && pk.getExtensions() != null &&
                pk.getExtensions().containsKey("global")) {
            sb.append(" GLOBAL");
        }

        return sb.toString();
    }

    @Override
    public String buildUniqueConstraint(JQuickTableDefinition table, JQuickUniqueConstraint uc) {
        StringBuilder sb = new StringBuilder();
        if (uc.getConstraintName() != null && !uc.getConstraintName().isEmpty()) {
            sb.append("CONSTRAINT ").append(quoteIdentifier(table, uc.getConstraintName())).append(SPACE);
        }
        sb.append("UNIQUE (");
        sb.append(formatColumnList(table, uc.getColumns()));
        sb.append(")");
        // 全局索引（OceanBase MySQL 模式特有）
        if (MODE_MYSQL.equals(mode) && uc.getExtensions() != null &&
                uc.getExtensions().containsKey("global")) {
            sb.append(" GLOBAL");
        }

        return sb.toString();
    }

    @Override
    public String buildForeignKey(JQuickTableDefinition table, JQuickForeignKeyConstraint fk) {
        StringBuilder sb = new StringBuilder();
        if (fk.getConstraintName() != null && !fk.getConstraintName().isEmpty()) {
            sb.append("CONSTRAINT ").append(quoteIdentifier(table, fk.getConstraintName())).append(SPACE);
        }
        sb.append("FOREIGN KEY (");
        sb.append(formatColumnList(table, fk.getColumns()));
        sb.append(") REFERENCES ").append(quoteIdentifier(table, fk.getReferencedTable()));
        sb.append(" (").append(formatColumnList(table, fk.getReferencedColumns())).append(")");
        if (fk.getOnDelete() != null) {
            sb.append(" ON DELETE ").append(convertForeignKeyAction(fk.getOnDelete()));
        }
        if (fk.getOnUpdate() != null) {
            sb.append(" ON UPDATE ").append(convertForeignKeyAction(fk.getOnUpdate()));
        }

        return sb.toString();
    }

    @Override
    public String buildIndex(JQuickTableDefinition table, JQuickIndexDefinition index) {
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE ");
        if (index.isUnique()) {
            sb.append("UNIQUE ");
        }
        sb.append("INDEX ").append(quoteIdentifier(table, index.getIndexName()));
        sb.append(" ON ").append("${tableName}").append(" (");
        sb.append(formatColumnList(table, index.getColumns()));
        sb.append(")");
        // 索引类型
        if (index.getType() != null) {
            if ("BTREE".equalsIgnoreCase(index.getType())) {
                sb.append(" USING BTREE");
            } else if ("HASH".equalsIgnoreCase(index.getType())) {
                sb.append(" USING HASH");
            }
        }
        // 全局索引（OceanBase 特有）
        if (index.hasExtension("global")) {
            Boolean global = index.getExtension("global");
            if (global != null && global) {
                sb.append(" GLOBAL");
            }
        } else if (MODE_MYSQL.equals(mode)) {
            // MySQL 模式下默认局部索引
        }
        // 索引注释
        if (index.getComment() != null && !index.getComment().isEmpty()) {
            sb.append(" COMMENT '").append(escapeString(index.getComment())).append("'");
        }

        return sb.toString();
    }

    @Override
    public String buildModifyColumn(JQuickTableDefinition table, String tableName, JQuickColumnDefinition column) {
        if (MODE_ORACLE.equals(mode)) {
            return buildOracleModifyColumn(table, tableName, column);
        }
        return buildMySQLModifyColumn(table, tableName, column);
    }

    /**
     * MySQL 模式修改列
     */
    private String buildMySQLModifyColumn(JQuickTableDefinition table, String tableName, JQuickColumnDefinition column) {
        StringBuilder sb = new StringBuilder();
        sb.append("ALTER TABLE ").append(quoteIdentifier(table, tableName));
        sb.append(" MODIFY COLUMN ").append(quoteIdentifier(table, column.getColumnName()));
        sb.append(" ").append(getDataTypeString(table, column.getDataType()));

        if (!column.isNullable()) {
            sb.append(" NOT NULL");
        }

        if (column.getDefaultValue() != null && !column.isAutoIncrement()) {
            sb.append(" DEFAULT ").append(formatDefaultValue(column.getDefaultValue()));
        }

        if (column.getComment() != null && !column.getComment().isEmpty()) {
            sb.append(" COMMENT '").append(escapeString(column.getComment())).append("'");
        }

        return sb.toString();
    }

    /**
     * Oracle 模式修改列
     */
    private String buildOracleModifyColumn(JQuickTableDefinition table, String tableName, JQuickColumnDefinition column) {
        StringBuilder sb = new StringBuilder();
        sb.append("ALTER TABLE ").append(quoteIdentifier(table, tableName));
        sb.append(" MODIFY ").append(quoteIdentifier(table, column.getColumnName()));
        sb.append(" ").append(getDataTypeString(table, column.getDataType()));

        if (!column.isNullable()) {
            sb.append(" NOT NULL");
        }

        if (column.getDefaultValue() != null && !column.isAutoIncrement()) {
            sb.append(" DEFAULT ").append(formatDefaultValue(column.getDefaultValue()));
        }

        return sb.toString();
    }

    @Override
    public String buildChangeColumn(JQuickTableDefinition table, String tableName,
                                    String oldName, JQuickColumnDefinition newColumn) {
        if (MODE_ORACLE.equals(mode)) {
            return buildOracleChangeColumn(table, tableName, oldName, newColumn);
        }
        return buildMySQLChangeColumn(table, tableName, oldName, newColumn);
    }

    /**
     * MySQL 模式重命名列
     */
    private String buildMySQLChangeColumn(JQuickTableDefinition table, String tableName, String oldName, JQuickColumnDefinition newColumn) {
        StringBuilder sb = new StringBuilder();
        sb.append("ALTER TABLE ").append(quoteIdentifier(table, tableName));
        sb.append(" CHANGE ").append(quoteIdentifier(table, oldName));
        sb.append(" ").append(quoteIdentifier(table, newColumn.getColumnName()));
        sb.append(" ").append(getDataTypeString(table, newColumn.getDataType()));
        if (!newColumn.isNullable()) {
            sb.append(" NOT NULL");
        }

        if (newColumn.getDefaultValue() != null && !newColumn.isAutoIncrement()) {
            sb.append(" DEFAULT ").append(formatDefaultValue(newColumn.getDefaultValue()));
        }

        return sb.toString();
    }

    /**
     * Oracle 模式重命名列
     */
    private String buildOracleChangeColumn(JQuickTableDefinition table, String tableName, String oldName, JQuickColumnDefinition newColumn) {
        StringBuilder sb = new StringBuilder();
        if (!oldName.equals(newColumn.getColumnName())) {
            sb.append("ALTER TABLE ").append(quoteIdentifier(table, tableName));
            sb.append(" RENAME COLUMN ").append(quoteIdentifier(table, oldName));
            sb.append(" TO ").append(quoteIdentifier(table, newColumn.getColumnName()));
        }

        return sb.toString();
    }

    @Override
    public String buildAddColumn(JQuickTableDefinition table, String tableName, JQuickColumnDefinition column) {
        StringBuilder sb = new StringBuilder();
        sb.append("ALTER TABLE ").append(quoteIdentifier(table, tableName));
        sb.append(" ADD ");

        if (MODE_ORACLE.equals(mode)) {
            sb.append("(");
        }

        sb.append(quoteIdentifier(table, column.getColumnName()));
        sb.append(" ").append(getDataTypeString(table, column.getDataType()));

        if (!column.isNullable()) {
            sb.append(" NOT NULL");
        }

        if (column.getDefaultValue() != null && !column.isAutoIncrement()) {
            sb.append(" DEFAULT ").append(formatDefaultValue(column.getDefaultValue()));
        }

        if (MODE_ORACLE.equals(mode)) {
            sb.append(")");
        }

        // 列位置（MySQL 模式）
        if (MODE_MYSQL.equals(mode) && column.getPosition() != null) {
            if (column.getPosition().getType() == com.github.paohaijiao.enums.JQuickPositionType.FIRST) {
                sb.append(" FIRST");
            } else if (column.getPosition().getAfterColumn() != null) {
                sb.append(" AFTER ").append(quoteIdentifier(table, column.getPosition().getAfterColumn()));
            }
        }

        return sb.toString();
    }

    @Override
    public String buildDropColumn(JQuickTableDefinition table, String tableName, String columnName) {
        StringBuilder sb = new StringBuilder();
        sb.append("ALTER TABLE ").append(quoteIdentifier(table, tableName));
        sb.append(" DROP ");

        if (MODE_ORACLE.equals(mode)) {
            sb.append("COLUMN ");
        }

        sb.append(quoteIdentifier(table, columnName));

        if (MODE_ORACLE.equals(mode) && table.getExtensions() != null &&
                table.getExtensions().containsKey("dropColumnCascade")) {
            Boolean cascade = (Boolean) table.getExtensions().get("dropColumnCascade");
            if (cascade != null && cascade) {
                sb.append(" CASCADE CONSTRAINTS");
            }
        }

        return sb.toString();
    }

    @Override
    public String buildDropTable(JQuickTableDefinition table, String tableName, boolean ifExists) {
        StringBuilder sb = new StringBuilder("DROP TABLE ");

        if (MODE_ORACLE.equals(mode) && ifExists) {
            // Oracle 模式需要先检查
            sb.append("IF EXISTS ");
        } else if (ifExists) {
            sb.append("IF EXISTS ");
        }
        sb.append(quoteIdentifier(table, tableName));
        if (MODE_ORACLE.equals(mode) && table.getExtensions() != null &&
                table.getExtensions().containsKey("cascade")) {
            Boolean cascade = (Boolean) table.getExtensions().get("cascade");
            if (cascade != null && cascade) {
                sb.append(" CASCADE CONSTRAINTS");
            }
        }
        return sb.toString();
    }

    @Override
    public String buildShowCreateTable(JQuickTableDefinition table, String tableName) {
        return "SHOW CREATE TABLE " + quoteIdentifier(table, tableName);
    }

    @Override
    public String buildDescribeTable(JQuickTableDefinition table, String tableName) {
        if (MODE_ORACLE.equals(mode)) {
            return "SELECT COLUMN_NAME, DATA_TYPE, NULLABLE, DATA_DEFAULT " + "FROM USER_TAB_COLUMNS WHERE TABLE_NAME = '" + tableName.toUpperCase() + "'";
        }
        return "DESCRIBE " + quoteIdentifier(table, tableName);
    }

    @Override
    public String buildInsert(JQuickTableDefinition table, JQuickRow row) {
        if (row == null || row.isEmpty() || table == null) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        sb.append("INSERT INTO ").append(quoteIdentifier(table, table.getTableName())).append(" (");
        List<String> columns = new ArrayList<>(row.keySet());
        sb.append(columns.stream().map(e -> quoteIdentifier(table, e)).collect(Collectors.joining(", ")));
        sb.append(") VALUES (");
        List<String> values = new ArrayList<>();
        for (String col : columns) {
            values.add(formatValue(row.get(col)));
        }
        sb.append(String.join(", ", values));
        sb.append(")");
        // Oracle 模式返回主键
        if (MODE_ORACLE.equals(mode) && !table.getPrimaryKeys().isEmpty()) {
            String pkColumn = table.getPrimaryKeys().get(0).getColumns().get(0);
            sb.append(" RETURNING ").append(quoteIdentifier(table, pkColumn)).append(" INTO ?");
        }
        return sb.toString();
    }

    @Override
    public String buildUpdate(JQuickTableDefinition table, JQuickRow row, String whereClause) {
        if (row == null || row.isEmpty() || table == null) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        sb.append("UPDATE ").append(quoteIdentifier(table, table.getTableName())).append(" SET ");
        List<String> setClauses = new ArrayList<>();
        for (Map.Entry<String, Object> entry : row.entrySet()) {
            setClauses.add(quoteIdentifier(table, entry.getKey()) + " = " + formatValue(entry.getValue()));
        }
        sb.append(String.join(", ", setClauses));
        if (whereClause != null && !whereClause.trim().isEmpty()) {
            sb.append(" WHERE ").append(whereClause);
        }
        return sb.toString();
    }

    @Override
    public String buildDelete(JQuickTableDefinition table, String whereClause) {
        if (table == null) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        sb.append("DELETE FROM ").append(quoteIdentifier(table, table.getTableName()));
        if (whereClause != null && !whereClause.trim().isEmpty()) {
            sb.append(" WHERE ").append(whereClause);
        }
        return sb.toString();
    }

    @Override
    public String buildSelect(JQuickTableDefinition table, List<String> columns, String whereClause) {
        if (table == null) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        sb.append("SELECT ");
        if (columns == null || columns.isEmpty()) {
            sb.append("*");
        } else {
            sb.append(columns.stream().map(e -> quoteIdentifier(table, e)).collect(Collectors.joining(", ")));
        }
        sb.append(" FROM ").append(quoteIdentifier(table, table.getTableName()));
        if (whereClause != null && !whereClause.trim().isEmpty()) {
            sb.append(" WHERE ").append(whereClause);
        }
        return sb.toString();
    }
    private boolean isTemporary(JQuickTableDefinition table) {
        return table.getExtensions() != null && table.getExtensions().containsKey("temporary") && (Boolean) table.getExtensions().get("temporary");
    }

    private boolean ifNotExists(JQuickTableDefinition table) {
        return table.getExtensions() != null && table.getExtensions().containsKey("ifNotExists") && (Boolean) table.getExtensions().get("ifNotExists");
    }

    private String buildOracleTableComment(JQuickTableDefinition table) {
        if (table.getComment() != null && !table.getComment().isEmpty()) {
            return "COMMENT ON TABLE " + quoteIdentifier(table, table.getTableName()) +
                    " IS '" + escapeString(table.getComment()) + "'";
        }
        return null;
    }


    /**
     * 构建创建表分组语句
     */
    public String buildCreateTableGroup(String groupName, String locality, String primaryZone) {
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE TABLEGROUP ").append(quoteIdentifier(null, groupName));

        if (locality != null && !locality.isEmpty()) {
            sb.append(" LOCALITY = '").append(locality).append("'");
        }

        if (primaryZone != null && !primaryZone.isEmpty()) {
            sb.append(" PRIMARY_ZONE = '").append(primaryZone).append("'");
        }

        return sb.toString();
    }

    /**
     * 构建删除表分组语句
     */
    public String buildDropTableGroup(String groupName, boolean ifExists) {
        StringBuilder sb = new StringBuilder("DROP TABLEGROUP ");
        if (ifExists) {
            sb.append("IF EXISTS ");
        }
        sb.append(quoteIdentifier(null, groupName));
        return sb.toString();
    }

    /**
     * 构建创建租户语句
     */
    public String buildCreateTenant(String tenantName, String resourceUnit, String zoneList, String locality) {
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE TENANT ").append(tenantName);
        sb.append(" RESOURCE_POOL_LIST = ('").append(resourceUnit).append("')");

        if (zoneList != null && !zoneList.isEmpty()) {
            sb.append(" ZONE_LIST = ('").append(zoneList).append("')");
        }

        if (locality != null && !locality.isEmpty()) {
            sb.append(" LOCALITY = '").append(locality).append("'");
        }

        sb.append(" SET variables = 'ob_compatibility_mode=")
                .append(mode.toLowerCase()).append("'");

        return sb.toString();
    }

    /**
     * 构建切换租户语句
     */
    public String buildUseTenant(String tenantName) {
        return "USE " + tenantName;
    }

    /**
     * 构建创建资源池语句
     */
    public String buildCreateResourcePool(String poolName, String unitName, String unitConfig, int unitCount, String zoneList) {
        String sb = "CREATE RESOURCE POOL " + poolName +
                " UNIT = '" + unitName + "'" +
                ", UNIT_NUM = " + unitCount +
                ", ZONE_LIST = ('" + zoneList + "')";
        return sb;
    }

    /**
     * 构建创建资源单元语句
     */
    public String buildCreateResourceUnit(String unitName, int maxCPU, int minCPU, long maxMemory, long minMemory, long maxDisk) {
        String sb = "CREATE RESOURCE UNIT " + unitName +
                " MAX_CPU = " + maxCPU +
                ", MIN_CPU = " + minCPU +
                ", MAX_MEMORY = '" + maxMemory + "G'" +
                ", MIN_MEMORY = '" + minMemory + "G'" +
                ", MAX_DISK_SIZE = '" + maxDisk + "G'";
        return sb;
    }

    /**
     * 构建备份语句
     */
    public String buildBackupDatabase(String backupPath) {
        return "BACKUP DATABASE TO '" + backupPath + "'";
    }

    /**
     * 构建恢复语句
     */
    public String buildRestoreDatabase(String backupPath) {
        return "RESTORE DATABASE FROM '" + backupPath + "'";
    }


    @Override
    protected void appendNullClause(StringBuilder def, JQuickColumnDefinition column) {
        // 已在列定义中处理
    }

    @Override
    protected void appendDefaultClause(StringBuilder def, JQuickColumnDefinition column) {
        // 已在列定义中处理
    }

    @Override
    protected void appendColumnComment(StringBuilder def, JQuickColumnDefinition column) {
        // 已在列定义中处理
    }

    @Override
    protected String getSpecialDefaultKeyword(String value) {
        if (value == null) return null;
        String upperValue = value.toUpperCase();
        if (MODE_ORACLE.equals(mode)) {
            if ("CURRENT_TIMESTAMP".equals(upperValue) || "NOW()".equals(upperValue)) {
                return "CURRENT_TIMESTAMP";
            }
            if ("SYSDATE".equals(upperValue)) {
                return "SYSDATE";
            }
            if ("CURRENT_DATE".equals(upperValue)) {
                return "CURRENT_DATE";
            }
            if ("USER".equals(upperValue) || "CURRENT_USER".equals(upperValue)) {
                return "USER";
            }
        } else {
            if ("CURRENT_TIMESTAMP".equals(upperValue) || "NOW()".equals(upperValue)) {
                return "CURRENT_TIMESTAMP";
            }
            if ("CURRENT_DATE".equals(upperValue)) {
                return "CURRENT_DATE";
            }
            if ("CURRENT_TIME".equals(upperValue)) {
                return "CURRENT_TIME";
            }
        }
        return null;
    }

    @Override
    protected String formatBooleanDefault(boolean value) {
        if (MODE_ORACLE.equals(mode)) {
            return value ? "1" : "0";
        }
        return value ? "1" : "0";
    }

    @Override
    protected String convertForeignKeyAction(JQuickForeignKeyAction action) {
        if (action == null) return "NO ACTION";
        switch (action) {
            case NO_ACTION:
                return "NO ACTION";
            case RESTRICT:
                return "RESTRICT";
            case CASCADE:
                return "CASCADE";
            case SET_NULL:
                return "SET NULL";
            case SET_DEFAULT:
                return "SET DEFAULT";
            default:
                return "NO ACTION";
        }
    }

}