package com.github.paohaijiao.dialect.impl;

/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Copyright (c) [2025-2099] Martin (goudingcheng@gmail.com)
 */

import com.github.paohaijiao.column.JQuickColumnDefinition;
import com.github.paohaijiao.connector.JQuickDataSourceConnector;
import com.github.paohaijiao.dataType.JQuickDataType;
import com.github.paohaijiao.dataType.JQuickDataTypeConverter;
import com.github.paohaijiao.dataType.impl.JQuickDB2DataTypeConverter;
import com.github.paohaijiao.dialect.JQuickAbsSQLDialect;
import com.github.paohaijiao.enums.JQuickForeignKeyAction;
import com.github.paohaijiao.extra.JQuickForeignKeyConstraint;
import com.github.paohaijiao.extra.JQuickIndexDefinition;
import com.github.paohaijiao.row.JQuickRow;
import com.github.paohaijiao.table.JQuickTableDefinition;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * DB2 方言实现
 * 支持 IBM DB2 数据库的 SQL 语法特性
 *
 * DB2 版本兼容性：
 * - LUW (Linux/Unix/Windows) 10.5+
 * - z/OS
 * - iSeries
 *
 * @author Martin
 * @version 1.0.0
 * @since 2026/4/15
 */
public class JQuickDB2Dialect extends JQuickAbsSQLDialect {

    protected static final String DB2_QUOTE = "\"";

    private static final String SEQ_SUFFIX = "_SEQ";

    @Override
    protected JQuickDataTypeConverter createDataTypeConvert() {
        return new JQuickDB2DataTypeConverter();
    }

    @Override
    protected String getQuoteKeyWord() {
        return DB2_QUOTE;
    }

    @Override
    public String getAutoIncrementKeyword(JQuickTableDefinition tableDefinition) {
        // DB2 使用 GENERATED BY DEFAULT AS IDENTITY
        return "GENERATED BY DEFAULT AS IDENTITY";
    }

    @Override
    protected void appendTableOptions(StringBuilder sql, JQuickTableDefinition table) {
        if (table.getExtensions() != null) {
            if (table.getExtensions().containsKey("tablespace")) {
                String tablespace = table.getExtensions().get("tablespace").toString();
                sql.append(" IN ").append(quoteIdentifier(table, tablespace));
            }
            if (table.getExtensions().containsKey("indexTablespace")) {
                String indexTablespace = table.getExtensions().get("indexTablespace").toString();
                sql.append(" INDEX IN ").append(quoteIdentifier(table, indexTablespace));
            }
            if (table.getExtensions().containsKey("longTablespace")) {
                String longTablespace = table.getExtensions().get("longTablespace").toString();
                sql.append(" LONG IN ").append(quoteIdentifier(table, longTablespace));
            }
            if (table.getExtensions().containsKey("dataCapture")) {
                String dataCapture = table.getExtensions().get("dataCapture").toString();
                sql.append(" DATA CAPTURE ").append(dataCapture.toUpperCase());
            }
            if (table.getExtensions().containsKey("compress")) {
                Boolean compress = (Boolean) table.getExtensions().get("compress");
                if (compress != null && compress) {
                    sql.append(" COMPRESS YES");
                } else {
                    sql.append(" COMPRESS NO");
                }
            }
            if (table.getExtensions().containsKey("audit")) {
                String audit = table.getExtensions().get("audit").toString();
                sql.append(" AUDIT ").append(audit.toUpperCase());
            }
            if (table.getExtensions().containsKey("volatile")) {
                Boolean volatile_ = (Boolean) table.getExtensions().get("volatile");
                if (volatile_ != null && volatile_) {
                    sql.append(" VOLATILE");
                }
            }
        }
    }

    @Override
    public String getDriverClass(JQuickDataSourceConnector connector) {
        if (connector != null && connector.getDriverClass() != null && !connector.getDriverClass().trim().isEmpty()) {
            return connector.getDriverClass();
        }
        return "com.ibm.db2.jcc.DB2Driver";
    }

    @Override
    public String getUrl(JQuickDataSourceConnector connector) {
        if (connector == null) {
            throw new IllegalArgumentException("Connector cannot be null");
        }
        if (connector.getUrl() != null && !connector.getUrl().trim().isEmpty()) {
            return connector.getUrl();
        }
        String host = connector.getHost();
        String port = connector.getPort();
        String database = connector.getSchema();      // 数据库名
        String username = connector.getUsername();
        String password = connector.getPassword();
        if (host == null || host.trim().isEmpty()) {
            throw new IllegalStateException("Host is required for DB2 connection");
        }
        String effectivePort = (port != null && !port.trim().isEmpty()) ? port : "50000";
        StringBuilder url = new StringBuilder();
        url.append("jdbc:db2://").append(host).append(":").append(effectivePort);
        if (database != null && !database.trim().isEmpty()) {
            url.append("/").append(database);
        }
        boolean hasParams = false;
        if (username != null && !username.trim().isEmpty()) {
            url.append("?user=").append(username);
            hasParams = true;
        }
        if (password != null && !password.trim().isEmpty()) {
            url.append(hasParams ? "&" : "?").append("password=").append(password);
            hasParams = true;
        }
        return url.toString();
    }

    @Override
    public String buildCreateTable(JQuickTableDefinition table) {
        StringBuilder sql = new StringBuilder();
        boolean isTemporary = false;
        if (table.getExtensions() != null && table.getExtensions().containsKey("temporary")) {
            Boolean temporary = (Boolean) table.getExtensions().get("temporary");
            if (temporary != null && temporary) {
                isTemporary = true;
                if (table.getExtensions().containsKey("globalTemporary")) {
                    Boolean global = (Boolean) table.getExtensions().get("globalTemporary");
                    if (global != null && global) {
                        sql.append("DECLARE GLOBAL TEMPORARY TABLE ");
                    } else {
                        sql.append("DECLARE LOCAL TEMPORARY TABLE ");
                    }
                } else {
                    sql.append("DECLARE LOCAL TEMPORARY TABLE ");
                }
            } else {
                sql.append("CREATE TABLE ");
            }
        } else {
            sql.append("CREATE TABLE ");
        }
        sql.append(quoteIdentifier(table, table.getTableName())).append(" (\n");
        appendColumnDefinitions(sql, table);
        appendPrimaryKey(sql, table);
        appendUniqueConstraints(sql, table);
        appendForeignKeys(sql, table);
        appendCheckConstraints(sql, table);
        removeTrailingComma(sql);
        sql.append(")");
        appendTableOptions(sql, table);
        if (isTemporary && table.getExtensions() != null) {
            if (table.getExtensions().containsKey("onCommitDeleteRows")) {
                Boolean deleteRows = (Boolean) table.getExtensions().get("onCommitDeleteRows");
                if (deleteRows != null && deleteRows) {
                    sql.append(" ON COMMIT DELETE ROWS");
                } else {
                    sql.append(" ON COMMIT PRESERVE ROWS");
                }
            }
            if (table.getExtensions().containsKey("notLogged")) {
                Boolean notLogged = (Boolean) table.getExtensions().get("notLogged");
                if (notLogged != null && notLogged) {
                    sql.append(" NOT LOGGED");
                }
            }
        }
        String tableComment = buildTableComment(table);
        if (tableComment != null && !tableComment.isEmpty()) {
            sql.append(";\n").append(tableComment);
        }
        return sql.toString();
    }

    /**
     * 追加检查约束
     */
    protected void appendCheckConstraints(StringBuilder sql, JQuickTableDefinition table) {
        if (table.getExtensions() != null && table.getExtensions().containsKey("checkConstraints")) {
            @SuppressWarnings("unchecked")
            List<Map<String, Object>> checks = (List<Map<String, Object>>) table.getExtensions().get("checkConstraints");
            if (checks != null) {
                for (Map<String, Object> check : checks) {
                    String constraintName = (String) check.get("name");
                    String condition = (String) check.get("condition");
                    if (condition != null && !condition.isEmpty()) {
                        sql.append(INDENT);
                        if (constraintName != null && !constraintName.isEmpty()) {
                            sql.append("CONSTRAINT ").append(quoteIdentifier(table, constraintName)).append(" ");
                        }
                        sql.append("CHECK (").append(condition).append(")");
                        sql.append(COMMA).append(NEW_LINE);
                    }
                }
            }
        }
    }

    /**
     * 构建表注释语句
     */
    protected String buildTableComment(JQuickTableDefinition table) {
        if (table.getComment() != null && !table.getComment().isEmpty()) {
            return "COMMENT ON TABLE " + quoteIdentifier(table, table.getTableName()) + " IS '" + escapeString(table.getComment()) + "'";
        }
        return null;
    }

    /**
     * 构建列注释语句
     */
    public String buildColumnComment(JQuickTableDefinition table, String tableName, JQuickColumnDefinition column) {
        if (column.getComment() != null && !column.getComment().isEmpty()) {
            return "COMMENT ON COLUMN " + quoteIdentifier(table, tableName) + "." + quoteIdentifier(table, column.getColumnName()) + " IS '" + escapeString(column.getComment()) + "'";
        }
        return null;
    }

    /**
     * 构建所有列注释语句
     */
    public String[] buildAllColumnComments(JQuickTableDefinition table, String tableName) {
        return table.getColumns().stream()
                .map(col -> buildColumnComment(table, tableName, col))
                .filter(comment -> comment != null && !comment.isEmpty())
                .toArray(String[]::new);
    }

    /**
     * 构建完整建表语句（包含注释）
     */
    public String buildCreateTableWithComments(JQuickTableDefinition table) {
        StringBuilder fullSql = new StringBuilder();
        fullSql.append(buildCreateTable(table));
        for (JQuickColumnDefinition column : table.getColumns()) {
            String columnComment = buildColumnComment(table, table.getTableName(), column);
            if (columnComment != null && !columnComment.isEmpty()) {
                fullSql.append(";\n").append(columnComment);
            }
        }
        return fullSql.toString();
    }

    @Override
    public String buildColumnDefinition(JQuickTableDefinition table, JQuickColumnDefinition column) {
        StringBuilder def = new StringBuilder();
        def.append(quoteIdentifier(table, column.getColumnName())).append(SPACE);
        // 数据类
        def.append(getDataTypeString(table, column.getDataType()));
        // 自增列
        if (column.isAutoIncrement()) {
            def.append(" ").append(getAutoIncrementKeyword(table));
            // 指定起始值和步长
            if (column.getExtensions() != null) {
                if (column.getExtensions().containsKey("identityStart")) {
                    def.append(" START WITH ").append(column.getExtensions().get("identityStart"));
                }
                if (column.getExtensions().containsKey("identityIncrement")) {
                    def.append(" INCREMENT BY ").append(column.getExtensions().get("identityIncrement"));
                }
            }
        }
        appendNullClause(def, column);
        appendDefaultClause(def, column);
        return def.toString();
    }

    @Override
    protected void appendNullClause(StringBuilder def, JQuickColumnDefinition column) {
        if (!column.isNullable()) {
            def.append(" NOT NULL");
        }
    }

    @Override
    protected void appendDefaultClause(StringBuilder def, JQuickColumnDefinition column) {
        if (column.getDefaultValue() != null && !column.isAutoIncrement()) {
            def.append(" DEFAULT ").append(formatDefaultValue(column.getDefaultValue()));
        }
    }

    @Override
    protected void appendColumnComment(StringBuilder def, JQuickColumnDefinition column) {
        // DB2 使用 COMMENT ON 语句，不在列定义中
    }

    @Override
    protected String getSpecialDefaultKeyword(String value) {
        if (value == null) {
            return null;
        }
        String upperValue = value.toUpperCase();
        if ("CURRENT_TIMESTAMP".equals(upperValue) || "NOW()".equals(upperValue)) {
            return "CURRENT TIMESTAMP";
        }
        if ("CURRENT_DATE".equals(upperValue)) {
            return "CURRENT DATE";
        }
        if ("CURRENT_TIME".equals(upperValue)) {
            return "CURRENT TIME";
        }
        if ("CURRENT_USER".equals(upperValue)) {
            return "CURRENT USER";
        }
        if ("USER".equals(upperValue)) {
            return "USER";
        }
        if ("CURRENT_SCHEMA".equals(upperValue)) {
            return "CURRENT SCHEMA";
        }
        return null;
    }

    @Override
    protected String formatBooleanDefault(boolean value) {
        return value ? "1" : "0";
    }

    @Override
    protected String convertForeignKeyAction(JQuickForeignKeyAction action) {
        if (action == null) {
            return "NO ACTION";
        }
        switch (action) {
            case NO_ACTION:
                return "NO ACTION";
            case RESTRICT:
                return "RESTRICT";
            case CASCADE:
                return "CASCADE";
            case SET_NULL:
                return "SET NULL";
            case SET_DEFAULT:
                return "SET DEFAULT";
            default:
                return "NO ACTION";
        }
    }

    @Override
    public String buildModifyColumn(JQuickTableDefinition table, String tableName, JQuickColumnDefinition column) {
        StringBuilder sb = new StringBuilder();
        sb.append("ALTER TABLE ").append(quoteIdentifier(table, tableName));
        sb.append(" ALTER COLUMN ").append(quoteIdentifier(table, column.getColumnName()));
        sb.append(" SET DATA TYPE ").append(getDataTypeString(table, column.getDataType()));
        if (!column.isNullable()) {
            sb.append(" NOT NULL");
        }
        if (column.getDefaultValue() != null && !column.isAutoIncrement()) {
            sb.append(" DEFAULT ").append(formatDefaultValue(column.getDefaultValue()));
        }
        return sb.toString();
    }

    @Override
    public String buildChangeColumn(JQuickTableDefinition table, String tableName, String oldName, JQuickColumnDefinition newColumn) {
        StringBuilder sb = new StringBuilder();
        if (!oldName.equals(newColumn.getColumnName())) {
            sb.append("ALTER TABLE ").append(quoteIdentifier(table, tableName));
            sb.append(" RENAME COLUMN ").append(quoteIdentifier(table, oldName));
            sb.append(" TO ").append(quoteIdentifier(table, newColumn.getColumnName()));
            sb.append(";\n");
        }
        sb.append("ALTER TABLE ").append(quoteIdentifier(table, tableName));
        sb.append(" ALTER COLUMN ").append(quoteIdentifier(table, newColumn.getColumnName()));
        sb.append(" SET DATA TYPE ").append(getDataTypeString(table, newColumn.getDataType()));

        if (!newColumn.isNullable()) {
            sb.append(" NOT NULL");
        }
        if (newColumn.getDefaultValue() != null && !newColumn.isAutoIncrement()) {
            sb.append(" DEFAULT ").append(formatDefaultValue(newColumn.getDefaultValue()));
        }
        return sb.toString();
    }

    @Override
    public String buildShowCreateTable(JQuickTableDefinition table, String tableName) {
        // DB2 使用 db2look 工具或查询系统表
        return "SELECT TEXT FROM SYSCAT.TABLES WHERE TABNAME = '" + tableName.toUpperCase() + "'";
    }

    @Override
    public String buildDescribeTable(JQuickTableDefinition table, String tableName) {
        return "SELECT COLNAME, TYPENAME, NULLS, DEFAULT " +
                "FROM SYSCAT.COLUMNS " +
                "WHERE TABNAME = '" + tableName.toUpperCase() + "' " +
                "ORDER BY COLNO";
    }

    @Override
    public String buildInsert(JQuickTableDefinition table, JQuickRow row) {
        if (row == null || row.isEmpty() || table == null) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        sb.append("INSERT INTO ").append(quoteIdentifier(table, table.getTableName())).append(" (");
        List<String> columns = new ArrayList<>(row.keySet());
        sb.append(columns.stream().map(e -> quoteIdentifier(table, e)).collect(Collectors.joining(", ")));
        sb.append(") VALUES (");
        List<String> values = new ArrayList<>();
        for (String col : columns) {
            values.add(formatValue(row.get(col)));
        }
        sb.append(String.join(", ", values));
        sb.append(")");
        // DB2 使用 SELECT FROM FINAL TABLE 返回自增主键
        if (!table.getPrimaryKeys().isEmpty() && hasAutoIncrement(table)) {
            String pkColumn = table.getPrimaryKeys().get(0).getColumns().get(0);
            sb.insert(0, "SELECT " + quoteIdentifier(table, pkColumn) + " FROM FINAL TABLE (\n");
            sb.append("\n)");
        }
        return sb.toString();
    }

    @Override
    public String buildUpdate(JQuickTableDefinition table, JQuickRow row, String whereClause) {
        if (row == null || row.isEmpty() || table == null) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        sb.append("UPDATE ").append(quoteIdentifier(table, table.getTableName())).append(" SET ");
        List<String> setClauses = new ArrayList<>();
        for (Map.Entry<String, Object> entry : row.entrySet()) {
            setClauses.add(quoteIdentifier(table, entry.getKey()) + " = " + formatValue(entry.getValue()));
        }
        sb.append(String.join(", ", setClauses));
        if (whereClause != null && !whereClause.trim().isEmpty()) {
            sb.append(" WHERE ").append(whereClause);
        }

        return sb.toString();
    }

    @Override
    public String buildDelete(JQuickTableDefinition table, String whereClause) {
        if (table == null) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        sb.append("DELETE FROM ").append(quoteIdentifier(table, table.getTableName()));
        if (whereClause != null && !whereClause.trim().isEmpty()) {
            sb.append(" WHERE ").append(whereClause);
        }
        return sb.toString();
    }

    @Override
    public String buildSelect(JQuickTableDefinition table, List<String> columns, String whereClause) {
        if (table == null) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        sb.append("SELECT ");
        if (columns == null || columns.isEmpty()) {
            sb.append("*");
        } else {
            sb.append(columns.stream().map(e -> quoteIdentifier(table, e)).collect(Collectors.joining(", ")));
        }
        sb.append(" FROM ").append(quoteIdentifier(table, table.getTableName()));
        if (whereClause != null && !whereClause.trim().isEmpty()) {
            sb.append(" WHERE ").append(whereClause);
        }
        return sb.toString();
    }

    @Override
    public String buildIndex(JQuickTableDefinition table, JQuickIndexDefinition index) {
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE ");
        if (index.isUnique()) {
            sb.append("UNIQUE ");
        }
        // 聚集索引
        if (index.getType() != null && "CLUSTERED".equalsIgnoreCase(index.getType())) {
            sb.append("CLUSTER ");
        }
        sb.append("INDEX ").append(quoteIdentifier(table, index.getIndexName()));
        sb.append(" ON ").append("${tableName}").append(" (");
        sb.append(formatColumnList(table, index.getColumns()));
        sb.append(")");
        List<String> includeColumns = index.getIncludeColumns();
        if (includeColumns != null && !includeColumns.isEmpty()) {
            sb.append(" INCLUDE (");
            sb.append(formatColumnList(table, includeColumns));
            sb.append(")");
        }
        if (index.hasExtension("allowReverseScan")) {
            Boolean allowReverse = index.getExtension("allowReverseScan");
            if (allowReverse != null && allowReverse) {
                sb.append(" ALLOW REVERSE SCANS");
            }
        }
        // 页大小
        if (index.hasExtension("pageSize")) {
            Integer pageSize = index.getExtension("pageSize");
            if (pageSize != null) {
                sb.append(" PCTFREE ").append(pageSize);
            }
        }
        // 最小使用率
        if (index.hasExtension("minPctUsed")) {
            Integer minPctUsed = index.getExtension("minPctUsed");
            if (minPctUsed != null) {
                sb.append(" MINPCTUSED ").append(minPctUsed);
            }
        }

        return sb.toString();
    }

    /**
     * 检查是否有自增列
     */
    private boolean hasAutoIncrement(JQuickTableDefinition table) {
        return table.getColumns().stream().anyMatch(JQuickColumnDefinition::isAutoIncrement);
    }
    /**
     * 构建创建序列语句
     */
    public String buildCreateSequence(JQuickTableDefinition table, String sequenceName) {
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE SEQUENCE ").append(quoteIdentifier(table, sequenceName));
        Map<String, Object> seqParams = null;
        if (table.getExtensions() != null && table.getExtensions().containsKey("sequenceParams")) {
            @SuppressWarnings("unchecked")
            Map<String, Object> params = (Map<String, Object>) table.getExtensions().get("sequenceParams");
            seqParams = params;
        }

        if (seqParams != null) {
            if (seqParams.containsKey("startWith")) {
                sb.append(" START WITH ").append(seqParams.get("startWith"));
            }
            if (seqParams.containsKey("incrementBy")) {
                sb.append(" INCREMENT BY ").append(seqParams.get("incrementBy"));
            }
            if (seqParams.containsKey("minValue")) {
                sb.append(" MINVALUE ").append(seqParams.get("minValue"));
            }
            if (seqParams.containsKey("maxValue")) {
                sb.append(" MAXVALUE ").append(seqParams.get("maxValue"));
            }
            if (seqParams.containsKey("cache")) {
                sb.append(" CACHE ").append(seqParams.get("cache"));
            }
            if (seqParams.containsKey("cycle")) {
                Boolean cycle = (Boolean) seqParams.get("cycle");
                if (cycle != null && cycle) {
                    sb.append(" CYCLE");
                } else {
                    sb.append(" NO CYCLE");
                }
            }
            if (seqParams.containsKey("order")) {
                Boolean order = (Boolean) seqParams.get("order");
                if (order != null && order) {
                    sb.append(" ORDER");
                } else {
                    sb.append(" NO ORDER");
                }
            }
        }

        return sb.toString();
    }

    /**
     * 构建删除序列语句
     */
    public String buildDropSequence(JQuickTableDefinition table, String sequenceName) {
        return "DROP SEQUENCE " + quoteIdentifier(table, sequenceName) + " RESTRICT";
    }

    /**
     * 构建获取序列下一个值语句
     */
    public String buildGetSequenceNextValue(String sequenceName) {
        return "VALUES NEXT VALUE FOR " + sequenceName;
    }

    /**
     * 构建获取序列当前值语句
     */
    public String buildGetSequenceCurrentValue(String sequenceName) {
        return "VALUES PREVIOUS VALUE FOR " + sequenceName;
    }
    /**
     * 构建添加列语句
     */
    @Override
    public String buildAddColumn(JQuickTableDefinition table, String tableName, JQuickColumnDefinition column) {
        StringBuilder sb = new StringBuilder();
        sb.append("ALTER TABLE ").append(quoteIdentifier(table, tableName));
        sb.append(" ADD COLUMN ").append(quoteIdentifier(table, column.getColumnName()));
        sb.append(" ").append(getDataTypeString(table, column.getDataType()));
        if (!column.isNullable()) {
            sb.append(" NOT NULL");
        }
        if (column.getDefaultValue() != null && !column.isAutoIncrement()) {
            sb.append(" DEFAULT ").append(formatDefaultValue(column.getDefaultValue()));
        }
        return sb.toString();
    }

    /**
     * 构建删除列语句
     */
    @Override
    public String buildDropColumn(JQuickTableDefinition table, String tableName, String columnName) {
        return "ALTER TABLE " + quoteIdentifier(table, tableName) + " DROP COLUMN " + quoteIdentifier(table, columnName);
    }

    /**
     * 构建重命名列语句
     */
    public String buildRenameColumn(JQuickTableDefinition table, String tableName, String oldName, String newName) {
        return "ALTER TABLE " + quoteIdentifier(table, tableName) + " RENAME COLUMN " + quoteIdentifier(table, oldName) + " TO " + quoteIdentifier(table, newName);
    }

    /**
     * 构建设置 NOT NULL 语句
     */
    public String buildSetNotNull(JQuickTableDefinition table, String tableName, String columnName) {
        return "ALTER TABLE " + quoteIdentifier(table, tableName) + " ALTER COLUMN " + quoteIdentifier(table, columnName) + " SET NOT NULL";
    }

    /**
     * 构建删除 NOT NULL 语句
     */
    public String buildDropNotNull(JQuickTableDefinition table, String tableName, String columnName) {
        return "ALTER TABLE " + quoteIdentifier(table, tableName) + " ALTER COLUMN " + quoteIdentifier(table, columnName) + " DROP NOT NULL";
    }

    /**
     * 构建设置默认值语句
     */
    public String buildSetDefaultValue(JQuickTableDefinition table, String tableName, String columnName, Object defaultValue) {
        return "ALTER TABLE " + quoteIdentifier(table, tableName) + " ALTER COLUMN " + quoteIdentifier(table, columnName) + " SET DEFAULT " + formatDefaultValue(defaultValue);
    }

    /**
     * 构建删除默认值语句
     */
    public String buildDropDefaultValue(JQuickTableDefinition table, String tableName, String columnName) {
        return "ALTER TABLE " + quoteIdentifier(table, tableName) + " ALTER COLUMN " + quoteIdentifier(table, columnName) + " DROP DEFAULT";
    }
    /**
     * 构建删除表语句
     */
    @Override
    public String buildDropTable(JQuickTableDefinition table, String tableName, boolean ifExists) {
        StringBuilder sb = new StringBuilder();
        if (ifExists) {
            // DB2 没有 IF EXISTS，需要先检查
            sb.append("BEGIN\n");
            sb.append("  DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;\n");
            sb.append("  EXECUTE IMMEDIATE 'DROP TABLE ").append(quoteIdentifier(table, tableName)).append("';\n");
            sb.append("END");
        } else {
            sb.append("DROP TABLE ").append(quoteIdentifier(table, tableName));
        }
        return sb.toString();
    }

    /**
     * 构建清空表语句
     */
    @Override
    public String buildTruncateTable(JQuickTableDefinition table, String tableName) {
        return "TRUNCATE TABLE " + quoteIdentifier(table, tableName) + " IMMEDIATE";
    }

    /**
     * 构建重命名表语句
     */
    @Override
    public String buildRenameTable(JQuickTableDefinition table, String oldName, String newName) {
        return "RENAME TABLE " + quoteIdentifier(table, oldName) + " TO " + quoteIdentifier(table, newName);
    }

    /**
     * 构建激活表语句
     */
    public String buildActivateTable(JQuickTableDefinition table, String tableName) {
        return "ALTER TABLE " + quoteIdentifier(table, tableName) + " ACTIVATE NOT LOGGED INITIALLY";
    }
    /**
     * 构建添加主键语句
     */
    public String buildAddPrimaryKey(JQuickTableDefinition table, String tableName, String constraintName, List<String> columns) {
        StringBuilder sb = new StringBuilder("ALTER TABLE ");
        sb.append(quoteIdentifier(table, tableName));
        sb.append(" ADD ");
        if (constraintName != null && !constraintName.isEmpty()) {
            sb.append("CONSTRAINT ").append(quoteIdentifier(table, constraintName)).append(" ");
        }
        sb.append("PRIMARY KEY (").append(formatColumnList(table, columns)).append(")");
        return sb.toString();
    }

    /**
     * 构建添加唯一约束语句
     */
    public String buildAddUniqueConstraint(JQuickTableDefinition table, String tableName, String constraintName, List<String> columns) {
        StringBuilder sb = new StringBuilder("ALTER TABLE ");
        sb.append(quoteIdentifier(table, tableName));
        sb.append(" ADD ");
        if (constraintName != null && !constraintName.isEmpty()) {
            sb.append("CONSTRAINT ").append(quoteIdentifier(table, constraintName)).append(" ");
        }
        sb.append("UNIQUE (").append(formatColumnList(table, columns)).append(")");
        return sb.toString();
    }

    /**
     * 构建添加外键语句
     */
    public String buildAddForeignKey(JQuickTableDefinition table, String tableName, JQuickForeignKeyConstraint fk) {
        StringBuilder sb = new StringBuilder("ALTER TABLE ");
        sb.append(quoteIdentifier(table, tableName));
        sb.append(" ADD ");
        if (fk.getConstraintName() != null && !fk.getConstraintName().isEmpty()) {
            sb.append("CONSTRAINT ").append(quoteIdentifier(table, fk.getConstraintName())).append(" ");
        }
        sb.append("FOREIGN KEY (").append(formatColumnList(table, fk.getColumns()));
        sb.append(") REFERENCES ").append(quoteIdentifier(table, fk.getReferencedTable()));
        sb.append(" (").append(formatColumnList(table, fk.getReferencedColumns())).append(")");
        if (fk.getOnDelete() != null) {
            sb.append(" ON DELETE ").append(convertForeignKeyAction(fk.getOnDelete()));
        }
        if (fk.getOnUpdate() != null) {
            sb.append(" ON UPDATE ").append(convertForeignKeyAction(fk.getOnUpdate()));
        }
        // DB2 外键默认是 ENFORCED
        if (fk.getExtensions() != null && fk.getExtensions().containsKey("notEnforced")) {
            Boolean notEnforced = (Boolean) fk.getExtensions().get("notEnforced");
            if (notEnforced != null && notEnforced) {
                sb.append(" NOT ENFORCED");
            }
        } else {
            sb.append(" ENFORCED");
        }
        return sb.toString();
    }

    /**
     * 构建删除约束语句
     */
    public String buildDropConstraint(JQuickTableDefinition table, String tableName, String constraintName) {
        return "ALTER TABLE " + quoteIdentifier(table, tableName) + " DROP CONSTRAINT " + quoteIdentifier(table, constraintName);
    }

    /**
     * 构建启用约束语句
     */
    public String buildEnableConstraint(JQuickTableDefinition table, String tableName, String constraintName) {
        return "ALTER TABLE " + quoteIdentifier(table, tableName) + " ALTER CONSTRAINT " + quoteIdentifier(table, constraintName) + " ENFORCED";
    }

    /**
     * 构建禁用约束语句
     */
    public String buildDisableConstraint(JQuickTableDefinition table, String tableName, String constraintName) {
        return "ALTER TABLE " + quoteIdentifier(table, tableName) + " ALTER CONSTRAINT " + quoteIdentifier(table, constraintName) + " NOT ENFORCED";
    }
    /**
     * 构建创建范围分区表语句
     */
    public String buildCreateRangePartitionedTable(JQuickTableDefinition table, String partitionKey, List<Map<String, Object>> partitions) {
        StringBuilder sql = new StringBuilder();
        sql.append("CREATE TABLE ").append(quoteIdentifier(table, table.getTableName()));
        sql.append(" (\n");
        appendColumnDefinitions(sql, table);
        sql.append(") PARTITION BY RANGE (").append(quoteIdentifier(table, partitionKey)).append(")\n");
        sql.append("  (STARTING FROM (MINVALUE) ENDING AT (MAXVALUE) EVERY (1))\n");
        return sql.toString();
    }

    /**
     * 构建添加分区语句
     */
    public String buildAddPartition(JQuickTableDefinition table, String tableName, String partitionName, Object lessThanValue) {
        return "ALTER TABLE " + quoteIdentifier(table, tableName) + " ADD PARTITION " + quoteIdentifier(table, partitionName) + " STARTING FROM (" + formatValue(lessThanValue) + ")";
    }

    /**
     * 构建分离分区语句
     */
    public String buildDetachPartition(JQuickTableDefinition table, String tableName, String partitionName) {
        return "ALTER TABLE " + quoteIdentifier(table, tableName) + " DETACH PARTITION " + quoteIdentifier(table, partitionName);
    }
    /**
     * 构建分页查询语句
     */
    public String buildPaginationQuery(JQuickTableDefinition table, List<String> columns, String whereClause, String orderBy, int offset, int limit) {
        StringBuilder sql = new StringBuilder();
        String innerSelect = buildSelect(table, columns, whereClause);
        if (orderBy != null && !orderBy.isEmpty()) {
            innerSelect += " ORDER BY " + orderBy;
        }
        sql.append("SELECT * FROM (\n");
        sql.append("  SELECT ROW_NUMBER() OVER () AS ROW_NUM, t.* FROM (\n");
        sql.append("    ").append(innerSelect).append("\n");
        sql.append("  ) t\n");
        sql.append(") WHERE ROW_NUM > ").append(offset);
        if (limit > 0) {
            sql.append(" AND ROW_NUM <= ").append(offset + limit);
        }
        return sql.toString();
    }

    /**
     * 构建 FETCH FIRST 查询语句
     */
    public String buildFetchFirstQuery(JQuickTableDefinition table, List<String> columns, String whereClause, String orderBy, int limit) {
        StringBuilder sql = new StringBuilder();
        sql.append(buildSelect(table, columns, whereClause));
        if (orderBy != null && !orderBy.isEmpty()) {
            sql.append(" ORDER BY ").append(orderBy);
        }
        sql.append(" FETCH FIRST ").append(limit).append(" ROWS ONLY");
        return sql.toString();
    }

    /**
     * 构建 WITH UR 语句（未提交读隔离级别）
     */
    public String buildWithUR(String query) {
        return query + " WITH UR";
    }

    /**
     * 构建 WITH RS 语句（读稳定性隔离级别）
     */
    public String buildWithRS(String query) {
        return query + " WITH RS";
    }


    /**
     * 构建收集表统计信息语句
     */
    public String buildRunstats(JQuickTableDefinition table, String tableName) {
        return "RUNSTATS ON TABLE " + quoteIdentifier(table, tableName) + " WITH DISTRIBUTION AND DETAILED INDEXES ALL";
    }

    /**
     * 构建重组表语句
     */
    public String buildReorgTable(JQuickTableDefinition table, String tableName) {
        return "REORG TABLE " + quoteIdentifier(table, tableName);
    }

    /**
     * 构建重组索引语句
     */
    public String buildReorgIndexes(JQuickTableDefinition table, String tableName) {
        return "REORG INDEXES ALL FOR TABLE " + quoteIdentifier(table, tableName);
    }

    /**
     * 构建刷新表语句
     */
    public String buildRefreshTable(JQuickTableDefinition table, String tableName) {
        return "REFRESH TABLE " + quoteIdentifier(table, tableName);
    }

    /**
     * 构建优化级别设置
     */
    public String buildOptimizationLevel(int level) {
        if (level >= 0 && level <= 9) {
            return "SET CURRENT QUERY OPTIMIZATION = " + level;
        }
        return "SET CURRENT QUERY OPTIMIZATION = 5";
    }

    /**
     * 构建并行度设置
     */
    public String buildParallelism(int degree) {
        if (degree > 0) {
            return "SET CURRENT DEGREE = " + degree;
        }
        return "SET CURRENT DEGREE = 1";
    }
}