package com.github.paohaijiao.dialect.impl;
// ==================== 1. Firebird 方言 ====================

/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import com.github.paohaijiao.column.JQuickColumnDefinition;
import com.github.paohaijiao.connector.JQuickDataSourceConnector;
import com.github.paohaijiao.dataType.JQuickDataTypeConverter;
import com.github.paohaijiao.dataType.impl.JQuickFirebirdDataTypeConverter;
import com.github.paohaijiao.dialect.JQuickAbsSQLDialect;
import com.github.paohaijiao.enums.JQuickForeignKeyAction;
import com.github.paohaijiao.extra.JQuickForeignKeyConstraint;
import com.github.paohaijiao.extra.JQuickIndexDefinition;
import com.github.paohaijiao.extra.JQuickPrimaryKeyConstraint;
import com.github.paohaijiao.extra.JQuickUniqueConstraint;
import com.github.paohaijiao.row.JQuickRow;
import com.github.paohaijiao.table.JQuickTableDefinition;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Firebird 方言实现
 * 开源关系型数据库，支持存储过程、触发器
 *
 * @author Martin
 * @version 1.0.0
 * @since 2026/4/16
 */
public class JQuickFirebirdDialect extends JQuickAbsSQLDialect {

    protected static final String FIREBIRD_QUOTE = "\"";

    @Override
    protected JQuickDataTypeConverter createDataTypeConvert() {
        return new JQuickFirebirdDataTypeConverter();
    }

    @Override
    protected String getQuoteKeyWord() {
        return FIREBIRD_QUOTE;
    }

    @Override
    public String getAutoIncrementKeyword(JQuickTableDefinition tableDefinition) {
        return "GENERATED BY DEFAULT AS IDENTITY";
    }

    @Override
    protected void appendTableOptions(StringBuilder sql, JQuickTableDefinition table) {
        if (table.getExtensions() != null) {
            // 表空间
            if (table.getExtensions().containsKey("tablespace")) {
                sql.append(" TABLESPACE ").append(table.getExtensions().get("tablespace"));
            }
        }
    }

    @Override
    public String getDriverClass(JQuickDataSourceConnector connector) {
        if (connector != null && connector.getDriverClass() != null && !connector.getDriverClass().trim().isEmpty()) {
            return connector.getDriverClass();
        }
        return "org.firebirdsql.jdbc.FBDriver";
    }

    @Override
    public String getUrl(JQuickDataSourceConnector connector) {
        if (connector == null) {
            throw new IllegalArgumentException("Connector cannot be null");
        }
        if (connector.getUrl() != null && !connector.getUrl().trim().isEmpty()) {
            return connector.getUrl();
        }
        String host = connector.getHost();
        String port = connector.getPort();
        String database = connector.getSchema();
        String username = connector.getUsername();
        String password = connector.getPassword();
        if (host == null || host.trim().isEmpty()) {
            throw new IllegalStateException("Host is required for Firebird connection");
        }
        if (database == null || database.trim().isEmpty()) {
            throw new IllegalStateException("Database path (schema) is required for Firebird connection");
        }
        String effectivePort = (port != null && !port.trim().isEmpty()) ? port : "3050";
        boolean isEmbedded = "embedded".equalsIgnoreCase(connector.getByKeyStr("connectionType"));
        StringBuilder url = new StringBuilder();
        if (isEmbedded) {
            url.append("jdbc:firebirdsql:embedded:");
            String dbPath = database.trim();
            if (dbPath.contains("\\")) {
                dbPath = dbPath.replace("\\", "/");
            }
            url.append(dbPath);

        } else {
            url.append("jdbc:firebirdsql://").append(host).append(":").append(effectivePort);
            String dbPath = database.trim();
            if (dbPath.startsWith("/") || dbPath.contains(":")) {
                url.append("/").append(dbPath);
            } else if (dbPath.startsWith("./")) {
                url.append("/").append(dbPath);
            } else {
                url.append("/").append(dbPath);
            }
        }
        boolean hasParams = url.toString().contains("?");
        if (!hasParams && !isEmbedded) {
            url.append("?");
            hasParams = true;
        }
        if (!hasParams) {
            url.append("?encoding=UTF-8");
            hasParams = true;
        } else if (url.toString().contains("?")) {
            url.append("&encoding=UTF-8");
        } else {
            url.append(";encoding=UTF-8");
        }
        if (username != null && !username.trim().isEmpty()) {
            if (url.toString().contains("?")) {
                url.append("&user=").append(username);
            } else {
                url.append(";user=").append(username);
            }
        }
        if (password != null && !password.trim().isEmpty()) {
            if (url.toString().contains("?")) {
                url.append("&password=").append(password);
            } else {
                url.append(";password=").append(password);
            }
        }

        return url.toString();
    }

    @Override
    public String buildCreateTable(JQuickTableDefinition table) {
        StringBuilder sql = new StringBuilder();
        sql.append("CREATE TABLE ");
        if (table.getExtensions() != null && table.getExtensions().containsKey("ifNotExists")) {
            Boolean ifNotExists = (Boolean) table.getExtensions().get("ifNotExists");
            if (ifNotExists != null && ifNotExists) {
                // Firebird 不支持 IF NOT EXISTS
            }
        }
        sql.append(quoteIdentifier(table, table.getTableName())).append(" (\n");
        List<JQuickColumnDefinition> columns = table.getColumns();
        for (int i = 0; i < columns.size(); i++) {
            JQuickColumnDefinition column = columns.get(i);
            sql.append(INDENT).append(quoteIdentifier(table, column.getColumnName()))
                    .append(" ").append(getDataTypeString(table, column.getDataType()));

            if (!column.isNullable()) {
                sql.append(" NOT NULL");
            }

            if (column.isAutoIncrement()) {
                sql.append(" ").append(getAutoIncrementKeyword(table));
            }

            if (column.getDefaultValue() != null && !column.isAutoIncrement()) {
                sql.append(" DEFAULT ").append(formatDefaultValue(column.getDefaultValue()));
            }

            if (i < columns.size() - 1) {
                sql.append(",");
            }
            sql.append(NEW_LINE);
        }
        // 主键
        if (!table.getPrimaryKeys().isEmpty()) {
            sql.append(COMMA).append(NEW_LINE);
            sql.append(INDENT).append(buildPrimaryKey(table, table.getPrimaryKeys().get(0)));
        }
        sql.append(")");
        appendTableOptions(sql, table);

        return sql.toString();
    }

    /**
     * 构建创建生成器（序列）语句
     */
    public String buildCreateGenerator(String generatorName, int startValue) {
        return "CREATE GENERATOR " + quoteIdentifier(null, generatorName) + ";\nSET GENERATOR " + quoteIdentifier(null, generatorName) + " TO " + startValue;
    }

    /**
     * 构建创建触发器（用于自增列）语句
     */
    public String buildCreateTriggerForIdentity(String tableName, String columnName, String generatorName) {
        String triggerName = (tableName + "_" + columnName + "_BI").toUpperCase();
        return "CREATE TRIGGER " + triggerName + " FOR " + tableName + "\n" +
                "ACTIVE BEFORE INSERT POSITION 0\n" +
                "AS\n" +
                "BEGIN\n" +
                "  IF (NEW." + columnName + " IS NULL) THEN\n" +
                "    NEW." + columnName + " = GEN_ID(" + generatorName + ", 1);\n" +
                "END";
    }

    @Override
    public String buildInsert(JQuickTableDefinition table, JQuickRow row) {
        if (row == null || row.isEmpty() || table == null) return "";
        StringBuilder sb = new StringBuilder();
        sb.append("INSERT INTO ").append(quoteIdentifier(table, table.getTableName())).append(" (");
        List<String> columns = new ArrayList<>(row.keySet());
        sb.append(columns.stream().map(e -> quoteIdentifier(table, e)).collect(Collectors.joining(", ")));
        sb.append(") VALUES (");
        List<String> values = new ArrayList<>();
        for (String col : columns) {
            values.add(formatValue(row.get(col)));
        }
        sb.append(String.join(", ", values));
        sb.append(")");
        // 返回自增值
        if (!table.getPrimaryKeys().isEmpty() && hasAutoIncrement(table)) {
            sb.append(" RETURNING ").append(quoteIdentifier(table, table.getPrimaryKeys().get(0).getColumns().get(0)));
        }
        return sb.toString();
    }

    @Override
    public String buildSelect(JQuickTableDefinition table, List<String> columns, String whereClause) {
        if (table == null) return "";
        StringBuilder sb = new StringBuilder();
        sb.append("SELECT ");
        if (table.getExtensions() != null && table.getExtensions().containsKey("first")) {
            sb.append("FIRST ").append(table.getExtensions().get("first")).append(" ");
        }
        if (table.getExtensions() != null && table.getExtensions().containsKey("skip")) {
            sb.append("SKIP ").append(table.getExtensions().get("skip")).append(" ");
        }
        if (columns == null || columns.isEmpty()) {
            sb.append("*");
        } else {
            sb.append(columns.stream().map(e -> quoteIdentifier(table, e)).collect(Collectors.joining(", ")));
        }
        sb.append(" FROM ").append(quoteIdentifier(table, table.getTableName()));
        if (whereClause != null && !whereClause.trim().isEmpty()) {
            sb.append(" WHERE ").append(whereClause);
        }
        return sb.toString();
    }

    private boolean hasAutoIncrement(JQuickTableDefinition table) {
        return table.getColumns().stream().anyMatch(JQuickColumnDefinition::isAutoIncrement);
    }

    @Override
    protected void appendNullClause(StringBuilder def, JQuickColumnDefinition column) {
    }

    @Override
    protected void appendDefaultClause(StringBuilder def, JQuickColumnDefinition column) {
    }

    @Override
    protected void appendColumnComment(StringBuilder def, JQuickColumnDefinition column) {
    }

    @Override
    protected String getSpecialDefaultKeyword(String value) {
        if (value == null) return null;
        String upper = value.toUpperCase();
        if ("CURRENT_TIMESTAMP".equals(upper)) return "CURRENT_TIMESTAMP";
        return null;
    }

    @Override
    protected String formatBooleanDefault(boolean value) {
        return value ? "1" : "0";
    }

    @Override
    protected String convertForeignKeyAction(JQuickForeignKeyAction action) {
        return "NO ACTION";
    }

    @Override
    public String buildPrimaryKey(JQuickTableDefinition table, JQuickPrimaryKeyConstraint pk) {
        StringBuilder sb = new StringBuilder();
        if (pk.getConstraintName() != null && !pk.getConstraintName().isEmpty()) {
            sb.append("CONSTRAINT ").append(quoteIdentifier(table, pk.getConstraintName())).append(" ");
        }
        sb.append("PRIMARY KEY (");
        sb.append(formatColumnList(table, pk.getColumns()));
        sb.append(")");
        return sb.toString();
    }

    @Override
    public String buildUniqueConstraint(JQuickTableDefinition table, JQuickUniqueConstraint uc) {
        StringBuilder sb = new StringBuilder();
        if (uc.getConstraintName() != null && !uc.getConstraintName().isEmpty()) {
            sb.append("CONSTRAINT ").append(quoteIdentifier(table, uc.getConstraintName())).append(" ");
        }
        sb.append("UNIQUE (");
        sb.append(formatColumnList(table, uc.getColumns()));
        sb.append(")");
        return sb.toString();
    }

    @Override
    public String buildForeignKey(JQuickTableDefinition table, JQuickForeignKeyConstraint fk) {
        StringBuilder sb = new StringBuilder();
        if (fk.getConstraintName() != null && !fk.getConstraintName().isEmpty()) {
            sb.append("CONSTRAINT ").append(quoteIdentifier(table, fk.getConstraintName())).append(" ");
        }
        sb.append("FOREIGN KEY (");
        sb.append(formatColumnList(table, fk.getColumns()));
        sb.append(") REFERENCES ").append(quoteIdentifier(table, fk.getReferencedTable()));
        sb.append(" (").append(formatColumnList(table, fk.getReferencedColumns())).append(")");
        return sb.toString();
    }

    @Override
    public String buildModifyColumn(JQuickTableDefinition table, String tableName, JQuickColumnDefinition column) {
        return "ALTER TABLE " + quoteIdentifier(table, tableName) + " ALTER COLUMN " + quoteIdentifier(table, column.getColumnName()) + " TYPE " + getDataTypeString(table, column.getDataType());
    }

    @Override
    public String buildChangeColumn(JQuickTableDefinition table, String tableName, String oldName, JQuickColumnDefinition newColumn) {
        StringBuilder sb = new StringBuilder();
        if (!oldName.equals(newColumn.getColumnName())) {
            sb.append("ALTER TABLE ").append(quoteIdentifier(table, tableName));
            sb.append(" ALTER COLUMN ").append(quoteIdentifier(table, oldName));
            sb.append(" TO ").append(quoteIdentifier(table, newColumn.getColumnName())).append(";\n");
        }
        sb.append(buildModifyColumn(table, tableName, newColumn));
        return sb.toString();
    }

    @Override
    public String buildShowCreateTable(JQuickTableDefinition table, String tableName) {
        return "SHOW TABLE " + quoteIdentifier(table, tableName);
    }

    @Override
    public String buildDescribeTable(JQuickTableDefinition table, String tableName) {
        return "SHOW TABLE " + quoteIdentifier(table, tableName);
    }

    @Override
    public String buildUpdate(JQuickTableDefinition table, JQuickRow row, String whereClause) {
        if (row == null || row.isEmpty() || table == null) return "";
        StringBuilder sb = new StringBuilder();
        sb.append("UPDATE ").append(quoteIdentifier(table, table.getTableName())).append(" SET ");
        List<String> setClauses = new ArrayList<>();
        for (Map.Entry<String, Object> entry : row.entrySet()) {
            setClauses.add(quoteIdentifier(table, entry.getKey()) + " = " + formatValue(entry.getValue()));
        }
        sb.append(String.join(", ", setClauses));
        if (whereClause != null && !whereClause.trim().isEmpty()) sb.append(" WHERE ").append(whereClause);
        return sb.toString();
    }

    @Override
    public String buildDelete(JQuickTableDefinition table, String whereClause) {
        if (table == null) return "";
        StringBuilder sb = new StringBuilder();
        sb.append("DELETE FROM ").append(quoteIdentifier(table, table.getTableName()));
        if (whereClause != null && !whereClause.trim().isEmpty()) sb.append(" WHERE ").append(whereClause);
        return sb.toString();
    }

    @Override
    public String buildIndex(JQuickTableDefinition table, JQuickIndexDefinition index) {
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE ");
        if (index.isUnique()) sb.append("UNIQUE ");
        sb.append("INDEX ").append(quoteIdentifier(table, index.getIndexName()));
        sb.append(" ON ").append("${tableName}").append(" (");
        sb.append(formatColumnList(table, index.getColumns()));
        sb.append(")");
        return sb.toString();
    }
}

